import asyncio
import enum
import ipaddress
import pathlib
from . import json_wrapper as json_wrapper, source_info as source_info
from .exceptions import ServerError as ServerError
from _typeshed import Incomplete
from types import ModuleType
from typing import Any

SYS_MOD_PATHS: Incomplete
IPAddress = ipaddress.IPv4Address | ipaddress.IPv6Address
KERNEL_VERSION: Incomplete

class Sentinel(enum.Enum):
    MISSING = ...

def retrieve_git_version(source_path: str) -> str: ...
def get_repo_info(source_path: str) -> dict[str, Any]: ...
def get_software_info() -> dict[str, Any]: ...
def hash_directory(dir_path: str | pathlib.Path, ignore_exts: list[str], ignore_dirs: list[str]) -> str: ...
def verify_source(path: str | pathlib.Path | None = None) -> tuple[str, bool] | None: ...
def load_system_module(name: str) -> ModuleType: ...
def get_unix_peer_credentials(writer: asyncio.StreamWriter, name: str) -> dict[str, int]: ...
def pretty_print_time(seconds: int) -> str: ...
def parse_ip_address(address: str) -> IPAddress | None: ...
