import asyncio
from . import ServerError as ServerError
from _typeshed import Incomplete

CAN_FMT: str
CAN_READER_LIMIT: Incomplete
KLIPPER_ADMIN_ID: int
KLIPPER_SET_NODE_CMD: int
KATAPULT_SET_NODE_CMD: int
CMD_QUERY_UNASSIGNED: int
CANBUS_RESP_NEED_NODEID: int

class CanNode:
    node_id: Incomplete
    def __init__(self, node_id: int, cansocket: CanSocket) -> None: ...
    async def read(self, n: int = -1, timeout: float | None = 2) -> bytes: ...
    async def readexactly(self, n: int, timeout: float | None = 2) -> bytes: ...
    async def readuntil(self, sep: bytes = b'\x03', timeout: float | None = 2) -> bytes: ...
    def write(self, payload: bytes | bytearray) -> None: ...
    async def write_with_response(self, payload: bytearray | bytes, resp_length: int, timeout: float | None = 2.0) -> bytes: ...
    def feed_data(self, data: bytes) -> None: ...
    def close(self) -> None: ...

class CanSocket:
    nodes: dict[int, CanNode]
    cansock: Incomplete
    input_buffer: bytes
    output_packets: list[bytes]
    input_busy: bool
    send_task: asyncio.Task | None
    closed: bool
    def __init__(self, interface: str) -> None: ...
    def register_node(self, node_id: int) -> CanNode: ...
    def remove_node(self, node_id: int) -> None: ...
    def send(self, can_id: int, payload: bytes = b'') -> None: ...
    def close(self) -> None: ...

async def query_klipper_uuids(can_socket: CanSocket) -> list[dict[str, str]]: ...
