from _typeshed import Incomplete

IOCParamSize: Incomplete
IOC_NONE: int
IOC_WRITE: int
IOC_READ: int

def IOC(direction: int, cmd_type: int, cmd_number: int, param_size: int) -> int: ...
def IO(cmd_type: int, cmd_number: int) -> int: ...
def IOR(cmd_type: int, cmd_number: int, param_size: IOCParamSize) -> int: ...
def IOW(cmd_type: int, cmd_number: int, param_size: IOCParamSize) -> int: ...
def IOWR(cmd_type: int, cmd_number: int, param_size: IOCParamSize) -> int: ...
