import pathlib
from ..components.shell_command import ShellCommandFactory as ShellCommandFactory
from ..server import Server as Server
from _typeshed import Incomplete
from dataclasses import dataclass
from typing import Any, Callable

MAX_PIP_VERSION: Incomplete
MIN_PYTHON_VERSION: Incomplete

class PipException(Exception): ...

@dataclass(frozen=True)
class PipVersionInfo:
    pip_version_string: str
    python_version_string: str
    @property
    def pip_version(self) -> tuple[int, ...]: ...
    @property
    def python_version(self) -> tuple[int, ...]: ...
    @property
    def needs_pip_update(self) -> bool: ...
    @property
    def max_pip_version(self) -> tuple[int, ...]: ...
    @property
    def max_pip_version_string(self) -> str: ...

class PipExecutor:
    pip_cmd: Incomplete
    response_hdlr: Incomplete
    def __init__(self, pip_cmd: str, response_handler: Callable[[str], None] | None = None) -> None: ...
    def call_pip_with_response(self, args: str, timeout: float | None = None, env: dict[str, str] | None = None) -> str: ...
    def call_pip(self, args: str, timeout: float | None = None, env: dict[str, str] | None = None) -> None: ...
    def get_pip_version(self) -> PipVersionInfo: ...
    def update_pip(self, version: str | None = None) -> None: ...
    def install_packages(self, packages: pathlib.Path | list[str], sys_env_vars: dict[str, Any] | None = None) -> None: ...
    def build_virtualenv(self, py_exec: pathlib.Path, args: str) -> None: ...

class AsyncPipExecutor:
    pip_cmd: Incomplete
    server: Incomplete
    notify_callback: Incomplete
    def __init__(self, pip_cmd: str, server: Server, notify_callback: Callable[[bytes], None] | None = None) -> None: ...
    def get_shell_cmd(self) -> ShellCommandFactory: ...
    async def call_pip_with_response(self, args: str, timeout: float = 30.0, attempts: int = 3, sys_env_vars: dict[str, Any] | None = None) -> str: ...
    async def call_pip(self, args: str, timeout: float = 30.0, attempts: int = 3, sys_env_vars: dict[str, Any] | None = None) -> None: ...
    async def get_pip_version(self) -> PipVersionInfo: ...
    async def update_pip(self, version: str | None = None) -> None: ...
    async def install_packages(self, packages: pathlib.Path | list[str], sys_env_vars: dict[str, Any] | None = None) -> None: ...
    async def build_virtualenv(self, py_exec: pathlib.Path, args: str) -> None: ...

def read_requirements_file(requirements_path: pathlib.Path) -> list[str]: ...
def parse_pip_version(pip_response: str) -> PipVersionInfo: ...
def prepare_install_args(packages: pathlib.Path | list[str]) -> str: ...
