import pathlib
from .exceptions import ServerError as ServerError
from dataclasses import dataclass
from importlib_metadata import Distribution, PackageMetadata as PackageMetadata
from typing import Any

def package_path() -> pathlib.Path: ...
def source_path() -> pathlib.Path: ...
def is_git_repo(src_path: pathlib.Path | None = None) -> bool: ...
def find_git_repo(src_path: pathlib.Path | None = None) -> pathlib.Path | None: ...
def is_dist_package(item_path: pathlib.Path | None = None) -> bool: ...
def package_version() -> str | None: ...
def read_asset(asset_name: str) -> str | None: ...
def get_asset_path() -> pathlib.Path | None: ...
def normalize_project_name(name: str) -> str: ...
def load_distribution_info(venv_path: pathlib.Path, project_name: str) -> PackageInfo: ...
def is_vitualenv_project(venv_path: pathlib.Path | None = None, pkg_path: pathlib.Path | None = None, project_name: str = 'moonraker') -> bool: ...

@dataclass(frozen=True)
class PackageInfo:
    dist_info: Distribution
    metadata: PackageMetadata
    release_info: dict[str, Any] | None
    direct_url_data: dict[str, Any] | None
