from enum import Flag

VERSION_PATTERN: str
GIT_VERSION_PATTERN: str

class ReleaseType(Flag):
    FINAL = ...
    ALPHA = ...
    BETA = ...
    RELEASE_CANDIDATE = ...
    POST = ...
    DEV = ...

class BaseVersion:
    def __init__(self, version: str) -> None: ...
    @property
    def full_version(self) -> str: ...
    @property
    def short_version(self) -> str: ...
    @property
    def release(self) -> str: ...
    @property
    def tag(self) -> str: ...
    @property
    def release_type(self) -> ReleaseType: ...
    @property
    def dev_count(self) -> int: ...
    def is_pre_release(self) -> bool: ...
    def is_post_release(self) -> bool: ...
    def is_dev_release(self) -> bool: ...
    def is_alpha_release(self) -> bool: ...
    def is_beta_release(self) -> bool: ...
    def is_release_candidate(self) -> bool: ...
    def is_final_release(self) -> bool: ...
    def is_valid_version(self) -> bool: ...
    def __eq__(self, __value: object) -> bool: ...
    def __lt__(self, __value: object) -> bool: ...
    def __le__(self, __value: object) -> bool: ...
    def __ne__(self, __value: object) -> bool: ...
    def __gt__(self, __value: object) -> bool: ...
    def __ge__(self, __value: object) -> bool: ...

class PyVersion(BaseVersion):
    local: str | None
    def __init__(self, version: str) -> None: ...
    @property
    def short_version(self) -> str: ...
    def bump_local_version(self, new_local: str) -> PyVersion: ...
    def convert_to_git(self) -> GitVersion: ...

class GitVersion(BaseVersion):
    def __init__(self, version: str) -> None: ...
    @property
    def dirty(self) -> bool: ...
    @property
    def inferred(self) -> bool: ...
    def is_fallback(self) -> bool: ...
    def infer_last_tag(self) -> str: ...
