import asyncio
import pathlib
from ..common import RequestType as RequestType, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from .database import MoonrakerDatabase as MoonrakerDatabase
from .http_client import HttpClient as HttpClient
from _typeshed import Incomplete
from typing import Any, Awaitable

MOONLIGHT_URL: str
UPDATE_CHECK_TIME: float

class Announcements:
    server: Incomplete
    entry_mgr: Incomplete
    eventloop: Incomplete
    update_timer: Incomplete
    request_lock: Incomplete
    dev_mode: Incomplete
    subscriptions: dict[str, RssFeed]
    stored_feeds: list[str]
    configured_feeds: list[str]
    def __init__(self, config: ConfigHelper) -> None: ...
    async def component_init(self) -> None: ...
    def add_internal_announcement(self, title: str, desc: str, url: str, priority: str, feed: str) -> dict[str, Any]: ...
    async def remove_announcement(self, entry_id: str) -> None: ...
    async def dismiss_announcement(self, entry_id, wake_time: int | None = None) -> None: ...
    async def get_announcements(self, include_dismissed: bool = False) -> list[dict[str, Any]]: ...
    def register_feed(self, name: str) -> None: ...
    def close(self) -> None: ...

class EntryManager:
    server: Incomplete
    announce_db: Incomplete
    entry_id_map: dict[str, str]
    next_key: int
    dismiss_handles: dict[str, asyncio.TimerHandle]
    def __init__(self, config: ConfigHelper) -> None: ...
    async def initialize(self) -> None: ...
    async def list_entries(self, include_dismissed: bool = True) -> list[dict[str, Any]]: ...
    def has_entry(self, entry_id: str) -> bool: ...
    def add_entry(self, entry: dict[str, Any]) -> Awaitable[None]: ...
    def remove_entry(self, entry_id: str) -> Awaitable[Any]: ...
    async def dismiss_entry(self, entry_id: str, wake_time: int | None = None) -> None: ...
    def prune_by_prefix(self, prefix: str, valid_ids: list[str]) -> bool: ...
    async def prune_by_feed(self, feed: str) -> bool: ...
    def close(self) -> None: ...

class RssFeed:
    server: Incomplete
    name: Incomplete
    entry_mgr: Incomplete
    client: HttpClient
    database: MoonrakerDatabase
    xml_file: Incomplete
    asset_url: Incomplete
    last_modified: int
    etag: str | None
    dev_xml_path: pathlib.Path | None
    def __init__(self, name: str, entry_mgr: EntryManager, dev_mode: bool) -> None: ...
    async def initialize(self) -> None: ...
    async def update_entries(self) -> bool: ...

def load_component(config: ConfigHelper) -> Announcements: ...
