import pathlib
import tornado.httputil
import tornado.web
from ..common import APIDefinition as APIDefinition, APITransport as APITransport, JsonRPC as JsonRPC, KlippyState as KlippyState, RequestType as RequestType, TransportType as TransportType, UserInfo as UserInfo, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from ..eventloop import EventLoop as EventLoop
from ..server import Server as Server
from ..utils import IPAddress as IPAddress, ServerError as ServerError, parse_ip_address as parse_ip_address, source_info as source_info
from .announcements import Announcements as Announcements
from .authorization import Authorization as Authorization
from .file_manager.file_manager import FileManager as FileManager
from .machine import Machine as Machine
from .template import JinjaTemplate as JinjaTemplate, TemplateFactory as TemplateFactory
from .websockets import WebSocket as WebSocket, WebsocketManager as WebsocketManager
from _typeshed import Incomplete
from tornado.httpserver import HTTPServer
from tornado.httputil import HTTPMessageDelegate, HTTPServerRequest as HTTPServerRequest
from tornado.routing import Rule, RuleRouter
from tornado.websocket import WebSocketHandler as WebSocketHandler
from typing import Any, AsyncGenerator, Callable, Coroutine

MessageDelgate = HTTPMessageDelegate | None
AuthComp = Authorization | None
APICallback = Callable[[WebRequest], Coroutine]
MAX_BODY_SIZE: Incomplete
MAX_WS_CONNS_DEFAULT: int
EXCLUDED_ARGS: Incomplete
AUTHORIZED_EXTS: Incomplete
DEFAULT_KLIPPY_LOG_PATH: str

class MutableRouter(RuleRouter):
    application: Incomplete
    pattern_to_rule: dict[str, Rule]
    def __init__(self, application: tornado.web.Application) -> None: ...
    def get_target_delegate(self, target: Any, request: tornado.httputil.HTTPServerRequest, **target_params) -> MessageDelgate: ...
    def has_rule(self, pattern: str) -> bool: ...
    def add_handler(self, pattern: str, target: Any, target_params: dict[str, Any] | None = None) -> None: ...
    def remove_handler(self, pattern: str) -> None: ...

class PrimaryRouter(MutableRouter):
    verbose_logging: Incomplete
    def __init__(self, config: ConfigHelper) -> None: ...
    @property
    def tornado_app(self) -> tornado.web.Application: ...
    def find_handler(self, request: HTTPServerRequest, **kwargs: Any) -> HTTPMessageDelegate | None: ...
    def log_request(self, handler: tornado.web.RequestHandler) -> None: ...

class InternalTransport(APITransport):
    server: Incomplete
    def __init__(self, server: Server) -> None: ...
    async def call_method(self, method_name: str, request_arguments: dict[str, Any] = {}, **kwargs) -> Any: ...

class MoonrakerApp:
    server: Incomplete
    json_rpc: Incomplete
    http_server: HTTPServer | None
    secure_server: HTTPServer | None
    template_cache: dict[str, JinjaTemplate]
    registered_base_handlers: list[str]
    max_upload_size: Incomplete
    cert_path: pathlib.Path
    key_path: pathlib.Path
    internal_transport: Incomplete
    mutable_router: Incomplete
    def __init__(self, config: ConfigHelper) -> None: ...
    @property
    def route_prefix(self): ...
    def parse_endpoint(self, http_path: str) -> str: ...
    def listen(self, host: str, port: int, ssl_port: int) -> None: ...
    def get_server(self) -> Server: ...
    def https_enabled(self) -> bool: ...
    async def close(self) -> None: ...
    def register_endpoint(self, endpoint: str, request_types: list[str] | RequestType, callback: APICallback, transports: list[str] | TransportType = ..., wrap_result: bool = True, content_type: str | None = None, auth_required: bool = True, is_remote: bool = False) -> None: ...
    def register_static_file_handler(self, pattern: str, file_path: str, force: bool = False) -> None: ...
    def register_upload_handler(self, pattern: str, location_prefix: str = 'server/files') -> None: ...
    def register_websocket_handler(self, pattern: str, handler: type[WebSocketHandler]) -> None: ...
    def register_debug_endpoint(self, endpoint: str, request_types: list[str] | RequestType, callback: APICallback, transports: list[str] | TransportType = ..., wrap_result: bool = True) -> None: ...
    def remove_endpoint(self, endpoint: str) -> None: ...
    async def load_template(self, asset_name: str) -> JinjaTemplate: ...

class AuthorizedRequestHandler(tornado.web.RequestHandler):
    server: Server
    auth_required: bool
    cors_enabled: bool
    def initialize(self) -> None: ...
    def set_default_headers(self) -> None: ...
    current_user: Incomplete
    async def prepare(self) -> None: ...
    def options(self, *args, **kwargs) -> None: ...
    def get_associated_websocket(self) -> WebSocket | None: ...
    def write_error(self, status_code: int, **kwargs) -> None: ...

class AuthorizedFileHandler(tornado.web.StaticFileHandler):
    server: Server
    cors_enabled: bool
    def initialize(self, path: str, default_filename: str | None = None) -> None: ...
    def set_default_headers(self) -> None: ...
    current_user: Incomplete
    async def prepare(self) -> None: ...
    def options(self, *args, **kwargs) -> None: ...
    def write_error(self, status_code: int, **kwargs) -> None: ...

class DynamicRequestHandler(AuthorizedRequestHandler):
    api_defintion: Incomplete
    wrap_result: Incomplete
    content_type: Incomplete
    auth_required: Incomplete
    def initialize(self, api_definition: APIDefinition | None = None, wrap_result: bool = True, content_type: str | None = None) -> None: ...
    def parse_args(self) -> dict[str, Any]: ...
    async def get(self, *args, **kwargs) -> None: ...
    async def post(self, *args, **kwargs) -> None: ...
    async def delete(self, *args, **kwargs) -> None: ...

class RPCHandler(AuthorizedRequestHandler, APITransport):
    auth_required: bool
    def initialize(self) -> None: ...
    @property
    def transport_type(self) -> TransportType: ...
    @property
    def user_info(self) -> UserInfo | None: ...
    @property
    def ip_addr(self) -> IPAddress | None: ...
    def screen_rpc_request(self, api_def: APIDefinition, req_type: RequestType, args: dict[str, Any]) -> None: ...
    def send_status(self, status: dict[str, Any], eventtime: float) -> None: ...
    async def post(self, *args, **kwargs) -> None: ...

class FileRequestHandler(AuthorizedFileHandler):
    def set_extra_headers(self, path: str) -> None: ...
    async def delete(self, path: str) -> None: ...
    path: Incomplete
    absolute_path: Incomplete
    modified: Incomplete
    async def get(self, path: str, include_body: bool = True) -> None: ...
    @classmethod
    async def get_content_nonblock(cls, evt_loop: EventLoop, abspath: str, start: int | None = None, end: int | None = None) -> AsyncGenerator[bytes, None]: ...

class FileUploadHandler(AuthorizedRequestHandler):
    location_prefix: Incomplete
    file_manager: FileManager
    max_upload_size: Incomplete
    parse_lock: Incomplete
    parse_failed: bool
    def initialize(self, location_prefix: str = 'server/files', max_upload_size: int = ...) -> None: ...
    async def prepare(self) -> None: ...
    async def data_received(self, chunk: bytes) -> None: ...
    async def post(self) -> None: ...

class AuthorizedErrorHandler(AuthorizedRequestHandler):
    async def prepare(self) -> None: ...
    def check_xsrf_cookie(self) -> None: ...
    def write_error(self, status_code: int, **kwargs) -> None: ...

class RedirectHandler(AuthorizedRequestHandler):
    auth_required: bool
    def initialize(self) -> None: ...
    async def get(self, *args, **kwargs) -> None: ...

class WelcomeHandler(tornado.web.RequestHandler):
    server: Server
    def initialize(self) -> None: ...
    async def get(self) -> None: ...

def load_component(config: ConfigHelper) -> MoonrakerApp: ...
