import contextlib
import pathlib
import sqlite3
from ..common import RequestType as RequestType, SqlTableDefinition as SqlTableDefinition, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from ..utils import Sentinel as Sentinel, ServerError as ServerError
from .klippy_connection import KlippyConnection as KlippyConnection
from _typeshed import Incomplete
from asyncio import Future, Task
from queue import Queue
from threading import Thread
from types import TracebackType
from typing import Any, Callable, Generator, Sequence

DBRecord = int | float | bool | str | list[Any] | dict[str, Any] | None
DBType = DBRecord
SqlParams = list[Any] | tuple[Any, ...] | dict[str, Any]
DATABASE_VERSION: int
SQL_DB_FILENAME: str
NAMESPACE_TABLE: str
REGISTRATION_TABLE: str
SCHEMA_TABLE: Incomplete
RECORD_ENCODE_FUNCS: dict[type, Callable[..., bytes]]
RECORD_DECODE_FUNCS: dict[int, Callable[..., DBRecord]]

def encode_record(value: DBRecord) -> bytes: ...
def decode_record(bvalue: bytes) -> DBRecord: ...
def getitem_with_default(item: dict, field: Any) -> Any: ...
def parse_namespace_key(key: list[str] | str) -> list[str]: ...
def generate_lmdb_entries(db_folder: pathlib.Path) -> Generator[tuple[str, str, bytes], Any, None]: ...

class MoonrakerDatabase:
    server: Incomplete
    eventloop: Incomplete
    registered_namespaces: set[str]
    registered_tables: set[str]
    backup_lock: Incomplete
    db_provider: Incomplete
    protected_namespaces: set[str]
    forbidden_namespaces: set[str]
    debug_counter: dict[str, int]
    unsafe_shutdowns: int
    def __init__(self, config: ConfigHelper) -> None: ...
    async def component_init(self) -> None: ...
    def get_database_path(self) -> str: ...
    @property
    def database_path(self) -> pathlib.Path: ...
    def insert_item(self, namespace: str, key: list[str] | str, value: DBType) -> Future[None]: ...
    def update_item(self, namespace: str, key: list[str] | str, value: DBType) -> Future[None]: ...
    def delete_item(self, namespace: str, key: list[str] | str) -> Future[Any]: ...
    def get_item(self, namespace: str, key: list[str] | str | None = None, default: Any = ...) -> Future[Any]: ...
    def insert_batch(self, namespace: str, records: dict[str, Any]) -> Future[None]: ...
    def move_batch(self, namespace: str, source_keys: list[str], dest_keys: list[str]) -> Future[None]: ...
    def delete_batch(self, namespace: str, keys: list[str]) -> Future[dict[str, Any]]: ...
    def get_batch(self, namespace: str, keys: list[str]) -> Future[dict[str, Any]]: ...
    def update_namespace(self, namespace: str, values: dict[str, DBRecord]) -> Future[None]: ...
    def clear_namespace(self, namespace: str) -> Future[None]: ...
    def sync_namespace(self, namespace: str, values: dict[str, DBRecord]) -> Future[None]: ...
    def ns_length(self, namespace: str) -> Future[int]: ...
    def ns_keys(self, namespace: str) -> Future[list[str]]: ...
    def ns_values(self, namespace: str) -> Future[list[Any]]: ...
    def ns_items(self, namespace: str) -> Future[list[tuple[str, Any]]]: ...
    def ns_contains(self, namespace: str, key: list[str] | str) -> Future[bool]: ...
    def sql_execute(self, sql: str, params: SqlParams = []) -> Future[SqliteCursorProxy]: ...
    def sql_executemany(self, sql: str, params: Sequence[SqlParams] = []) -> Future[SqliteCursorProxy]: ...
    def sql_executescript(self, sql: str) -> Future[SqliteCursorProxy]: ...
    def sql_commit(self) -> Future[None]: ...
    def sql_rollback(self) -> Future[None]: ...
    def queue_sql_callback(self, callback: Callable[[sqlite3.Connection], Any]) -> Future[Any]: ...
    def compact_database(self) -> Future[dict[str, int]]: ...
    def backup_database(self, bkp_path: pathlib.Path) -> Future[None]: ...
    def restore_database(self, restore_path: pathlib.Path) -> Future[dict[str, Any]]: ...
    def register_local_namespace(self, namespace: str, forbidden: bool = False, parse_keys: bool = False) -> NamespaceWrapper: ...
    def wrap_namespace(self, namespace: str, parse_keys: bool = True) -> NamespaceWrapper: ...
    def unregister_local_namespace(self, namespace: str) -> None: ...
    def drop_empty_namespace(self, namespace: str) -> Future[None]: ...
    def get_provider_wrapper(self) -> DBProviderWrapper: ...
    def get_backup_dir(self) -> pathlib.Path: ...
    def register_table(self, table_def: SqlTableDefinition) -> SqlTableWrapper: ...
    async def close(self) -> None: ...

class SqliteProvider(Thread):
    server: Incomplete
    asyncio_loop: Incomplete
    restored: bool
    command_queue: Queue[tuple[Future, Callable | None, tuple[Any, ...]]]
    sync_conn: Incomplete
    def __init__(self, config: ConfigHelper, db_path: pathlib.Path) -> None: ...
    @property
    def namespaces(self) -> set[str]: ...
    @property
    def tables(self) -> set[str]: ...
    def async_init(self) -> Future[str]: ...
    def run(self) -> None: ...
    def execute_db_function(self, command_func: Callable[..., _T], *args) -> Future[_T]: ...
    def setup_database(self) -> None: ...
    def get_namespace(self, conn: sqlite3.Connection, namespace: str, must_exist: bool = True) -> dict[str, Any]: ...
    def iter_namespace(self, conn: sqlite3.Connection, namespace: str, count: int = 1000) -> Generator[dict[str, Any], Any, None]: ...
    def clear_namespace(self, conn: sqlite3.Connection, namespace: str) -> None: ...
    def drop_empty_namespace(self, conn: sqlite3.Connection, namespace: str) -> None: ...
    def sync_namespace(self, conn: sqlite3.Connection, namespace: str, values: dict[str, DBRecord]) -> None: ...
    def get_namespace_length(self, conn: sqlite3.Connection, namespace: str) -> int: ...
    def get_namespace_keys(self, conn: sqlite3.Connection, namespace: str) -> list[str]: ...
    def get_namespace_values(self, conn: sqlite3.Connection, namespace: str) -> list[Any]: ...
    def get_namespace_items(self, conn: sqlite3.Connection, namespace: str) -> list[tuple[str, Any]]: ...
    def namespace_contains(self, conn: sqlite3.Connection, namespace: str, key: list[str] | str) -> bool: ...
    def insert_item(self, conn: sqlite3.Connection, namespace: str, key: list[str] | str, value: DBType) -> None: ...
    def update_item(self, conn: sqlite3.Connection, namespace: str, key: list[str] | str, value: DBType) -> None: ...
    def delete_item(self, conn: sqlite3.Connection, namespace: str, key: list[str] | str) -> Any: ...
    def get_item(self, conn: sqlite3.Connection, namespace: str, key: list[str] | str | None = None, default: Any = ...) -> Any: ...
    def insert_batch(self, conn: sqlite3.Connection, namespace: str, records: dict[str, Any]) -> None: ...
    def move_batch(self, conn: sqlite3.Connection, namespace: str, source_keys: list[str], dest_keys: list[str]) -> None: ...
    def delete_batch(self, conn: sqlite3.Connection, namespace: str, keys: list[str]) -> dict[str, Any]: ...
    def get_batch(self, conn: sqlite3.Connection, namespace: str, keys: list[str]) -> dict[str, Any]: ...
    def sql_execute(self, conn: sqlite3.Connection, statement: str, params: SqlParams) -> SqliteCursorProxy: ...
    def sql_executemany(self, conn: sqlite3.Connection, statement: str, params: Sequence[SqlParams]) -> SqliteCursorProxy: ...
    def sql_executescript(self, conn: sqlite3.Connection, script: str) -> SqliteCursorProxy: ...
    def sql_commit(self, conn: sqlite3.Connection) -> None: ...
    def sql_rollback(self, conn: sqlite3.Connection) -> None: ...
    def register_namespace(self, namespace: str) -> None: ...
    def register_table(self, table_def: SqlTableDefinition) -> None: ...
    def compact_database(self, conn: sqlite3.Connection) -> dict[str, int]: ...
    def backup_database(self, conn: sqlite3.Connection, bkp_path: pathlib.Path) -> None: ...
    def restore_database(self, conn: sqlite3.Connection, restore_path: pathlib.Path) -> dict[str, Any]: ...
    def get_provider_wapper(self) -> DBProviderWrapper: ...
    def is_restored(self) -> bool: ...
    def stop(self) -> Future[None]: ...

class DBProviderWrapper:
    server: Incomplete
    provider: Incomplete
    def __init__(self, provider: SqliteProvider) -> None: ...
    @property
    def connection(self) -> sqlite3.Connection: ...
    def iter_namespace(self, namespace: str, batch_count: int = 100) -> Generator[dict[str, Any], Any, None]: ...
    def get_namespace_keys(self, namespace: str) -> list[str]: ...
    def get_namespace_values(self, namespace: str) -> list[Any]: ...
    def get_namespace_items(self, namespace: str) -> list[tuple[str, Any]]: ...
    def get_namespace_length(self, namespace: str) -> int: ...
    def get_namespace(self, namespace: str) -> dict[str, Any]: ...
    def clear_namespace(self, namespace: str) -> None: ...
    def get_item(self, namespace: str, key: str | list[str], default: Any = ...) -> Any: ...
    def delete_item(self, namespace: str, key: str | list[str]) -> Any: ...
    def insert_item(self, namespace: str, key: str | list[str], value: DBType) -> None: ...
    def update_item(self, namespace: str, key: str | list[str], value: DBType) -> None: ...
    def get_batch(self, namespace: str, keys: list[str]) -> dict[str, Any]: ...
    def delete_batch(self, namespace: str, keys: list[str]) -> dict[str, Any]: ...
    def insert_batch(self, namespace: str, records: dict[str, Any]) -> None: ...
    def move_batch(self, namespace: str, source_keys: list[str], dest_keys: list[str]) -> None: ...
    def wipe_local_namespace(self, namespace: str) -> None: ...

class SqliteCursorProxy:
    def __init__(self, provider: SqliteProvider, cursor: sqlite3.Cursor) -> None: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def lastrowid(self) -> int | None: ...
    @property
    def description(self): ...
    @property
    def arraysize(self) -> int: ...
    def set_arraysize(self, size: int) -> Future[None]: ...
    def fetchone(self) -> Future[sqlite3.Row | None]: ...
    def fetchmany(self, size: int | None = None) -> Future[list[sqlite3.Row]]: ...
    def fetchall(self) -> Future[list[sqlite3.Row]]: ...

class SqlTableWrapper(contextlib.AbstractAsyncContextManager):
    def __init__(self, database: MoonrakerDatabase, table_def: SqlTableDefinition) -> None: ...
    @property
    def version(self) -> int: ...
    async def __aenter__(self) -> SqlTableWrapper: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def get_provider_wrapper(self) -> DBProviderWrapper: ...
    def queue_callback(self, callback: Callable[[sqlite3.Connection], Any]) -> Future[Any]: ...
    def execute(self, sql: str, params: SqlParams = []) -> Future[SqliteCursorProxy]: ...
    def executemany(self, sql: str, params: Sequence[SqlParams] = []) -> Future[SqliteCursorProxy]: ...
    def executescript(self, sql: str) -> Future[SqliteCursorProxy]: ...
    def commit(self) -> Future[None]: ...
    def rollback(self) -> Future[None]: ...

class NamespaceWrapper:
    namespace: Incomplete
    db: Incomplete
    eventloop: Incomplete
    server: Incomplete
    def __init__(self, namespace: str, database: MoonrakerDatabase, parse_keys: bool = False) -> None: ...
    @property
    def parse_keys(self) -> bool: ...
    @parse_keys.setter
    def parse_keys(self, val: bool) -> None: ...
    def get_provider_wrapper(self) -> DBProviderWrapper: ...
    def insert(self, key: list[str] | str, value: DBType) -> Future[None]: ...
    def update_child(self, key: list[str] | str, value: DBType) -> Future[None]: ...
    def update(self, value: dict[str, DBRecord]) -> Future[None]: ...
    def sync(self, value: dict[str, DBRecord]) -> Future[None]: ...
    def get(self, key: list[str] | str, default: Any = None) -> Future[Any]: ...
    def delete(self, key: list[str] | str) -> Future[Any]: ...
    def insert_batch(self, records: dict[str, Any]) -> Future[None]: ...
    def move_batch(self, source_keys: list[str], dest_keys: list[str]) -> Future[None]: ...
    def delete_batch(self, keys: list[str]) -> Future[dict[str, Any]]: ...
    def get_batch(self, keys: list[str]) -> Future[dict[str, Any]]: ...
    def length(self) -> Future[int]: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __getitem__(self, key: list[str] | str) -> Future[Any]: ...
    def __setitem__(self, key: list[str] | str, value: DBType) -> None: ...
    def __delitem__(self, key: list[str] | str): ...
    def __contains__(self, key: list[str] | str) -> bool: ...
    def contains(self, key: list[str] | str) -> Future[bool]: ...
    def keys(self) -> Future[list[str]]: ...
    def values(self) -> Future[list[Any]]: ...
    def items(self) -> Future[list[tuple[str, Any]]]: ...
    def pop(self, key: list[str] | str, default: Any = ...) -> Future[Any] | Task[Any]: ...
    def clear(self) -> Future[None]: ...

def load_component(config: ConfigHelper) -> MoonrakerDatabase: ...
