from ..confighelper import ConfigHelper as ConfigHelper
from _typeshed import Incomplete
from dbus_fast.aio import MessageBus, ProxyInterface as ProxyInterface
from typing import Any

STAT_PATH: str
DOC_URL: str

class DbusManager:
    Variant: Incomplete
    DbusError: Incomplete
    server: Incomplete
    bus: MessageBus | None
    polkit: ProxyInterface | None
    warned: bool
    polkit_subject: list[Any]
    def __init__(self, config: ConfigHelper) -> None: ...
    def is_connected(self) -> bool: ...
    async def component_init(self) -> None: ...
    async def check_permission(self, action: str, err_msg: str = '') -> bool: ...
    async def get_interface(self, bus_name: str, bus_path: str, interface_name: str) -> ProxyInterface: ...
    async def get_interfaces(self, bus_name: str, bus_path: str, interface_names: list[str]) -> list[ProxyInterface]: ...
    async def close(self) -> None: ...

def load_component(config: ConfigHelper) -> DbusManager: ...
