import asyncio
from ..common import BaseRemoteConnection as BaseRemoteConnection, RequestType as RequestType, TransportType as TransportType, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from ..server import Server as Server
from ..utils import get_unix_peer_credentials as get_unix_peer_credentials
from _typeshed import Incomplete

UNIX_BUFFER_LIMIT: Incomplete

class ExtensionManager:
    server: Incomplete
    agents: dict[str, BaseRemoteConnection]
    agent_methods: dict[int, list[str]]
    uds_server: asyncio.AbstractServer | None
    def __init__(self, config: ConfigHelper) -> None: ...
    def register_agent(self, connection: BaseRemoteConnection) -> None: ...
    def remove_agent(self, connection: BaseRemoteConnection) -> None: ...
    async def start_unix_server(self) -> None: ...
    def on_unix_socket_connected(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None: ...
    async def close(self) -> None: ...

class UnixSocketClient(BaseRemoteConnection):
    writer: Incomplete
    def __init__(self, server: Server, reader: asyncio.StreamReader, writer: asyncio.StreamWriter, peercred: dict[str, int]) -> None: ...
    async def write_to_socket(self, message: bytes | str) -> None: ...
    def close_socket(self, code: int, reason: str) -> None: ...

def load_component(config: ConfigHelper) -> ExtensionManager: ...
