from ..common import FieldTracker as FieldTracker, HistoryFieldData as HistoryFieldData, JobEvent as JobEvent, RequestType as RequestType, SqlTableDefinition as SqlTableDefinition, UserInfo as UserInfo, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from .database import DBProviderWrapper as DBProviderWrapper
from .file_manager.file_manager import FileManager as FileManager
from .job_state import JobState as JobState
from _typeshed import Incomplete
from typing import Any

Totals = dict[str, float | int]
AuxTotals = list[dict[str, Any]]
BASE_TOTALS: Incomplete
HIST_TABLE: str
TOTALS_TABLE: str

class TotalsSqlDefinition(SqlTableDefinition):
    name = TOTALS_TABLE
    prototype: Incomplete
    version: int
    def migrate(self, last_version: int, db_provider: DBProviderWrapper) -> None: ...

class HistorySqlDefinition(SqlTableDefinition):
    name = HIST_TABLE
    prototype: Incomplete
    version: int
    def migrate(self, last_version: int, db_provider: DBProviderWrapper) -> None: ...

class History:
    server: Incomplete
    file_manager: FileManager
    request_lock: Incomplete
    auxiliary_fields: list[HistoryFieldData]
    history_table: Incomplete
    totals_table: Incomplete
    job_totals: Totals
    aux_totals: AuxTotals
    current_job: PrinterJob | None
    current_job_id: int | None
    job_user: str
    job_paused: bool
    def __init__(self, config: ConfigHelper) -> None: ...
    async def component_init(self) -> None: ...
    async def add_job(self, job: PrinterJob) -> None: ...
    async def save_job(self, job: PrinterJob, job_id: int | None) -> int | None: ...
    async def delete_job(self, job_id: int | str) -> None: ...
    async def finish_job(self, status: str, pstats: dict[str, Any]) -> None: ...
    async def get_job(self, job_id: int | str) -> dict[str, Any] | None: ...
    def grab_job_metadata(self) -> None: ...
    def update_metadata(self, job_id: str) -> None: ...
    def send_history_event(self, evt_action: str) -> None: ...
    def register_auxiliary_field(self, new_field: HistoryFieldData) -> None: ...
    def tracking_enabled(self, check_paused: bool) -> bool: ...
    async def on_exit(self) -> None: ...

class PrinterJob:
    end_time: float | None
    filament_used: float
    filename: str
    metadata: dict[str, Any]
    print_duration: float
    status: str
    start_time: Incomplete
    total_duration: float
    auxiliary_data: list[dict[str, Any]]
    user: str
    def __init__(self, data: dict[str, Any] = {}) -> None: ...
    def finish(self, status: str, print_stats: dict[str, Any] = {}) -> None: ...
    def get(self, name: str) -> Any: ...
    def get_stats(self) -> dict[str, Any]: ...
    def set(self, name: str, val: Any) -> None: ...
    def set_aux_data(self, fields: list[HistoryFieldData]) -> None: ...
    def update_from_ps(self, data: dict[str, Any]) -> None: ...

def load_component(config: ConfigHelper) -> History: ...
