import asyncio
import pathlib
from ..confighelper import ConfigHelper as ConfigHelper
from ..server import Server as Server
from ..utils import ServerError as ServerError
from _typeshed import Incomplete
from io import BufferedWriter
from tornado.httputil import HTTPHeaders
from typing import Any, Callable

StrOrPath = str | pathlib.Path
MAX_BODY_SIZE: Incomplete
GITHUB_PREFIX: str

class HttpClient:
    server: Incomplete
    client: Incomplete
    response_cache: dict[str, HttpResponse]
    gh_rate_limit: int | None
    gh_limit_remaining: int | None
    gh_limit_reset_time: float | None
    def __init__(self, config: ConfigHelper) -> None: ...
    def register_cached_url(self, url: str, etag: str | None = None, last_modified: str | None = None) -> None: ...
    async def request(self, method: str, url: str, body: bytes | str | list[Any] | dict[str, Any] | None = None, headers: dict[str, Any] | None = None, connect_timeout: float = 5.0, request_timeout: float = 10.0, attempts: int = 1, retry_pause_time: float = 0.1, enable_cache: bool = False, send_etag: bool = True, send_if_modified_since: bool = True, basic_auth_user: str | None = None, basic_auth_pass: str | None = None) -> HttpResponse: ...
    async def get(self, url: str, headers: dict[str, Any] | None = None, **kwargs) -> HttpResponse: ...
    async def post(self, url: str, body: str | list[Any] | dict[str, Any] = '', headers: dict[str, Any] | None = None, **kwargs) -> HttpResponse: ...
    async def delete(self, url: str, headers: dict[str, Any] | None = None, **kwargs) -> HttpResponse: ...
    async def github_api_request(self, resource: str, attempts: int = 1, retry_pause_time: float = 0.1) -> HttpResponse: ...
    def github_api_stats(self) -> dict[str, Any]: ...
    async def get_file(self, url: str, content_type: str, connect_timeout: float = 5.0, request_timeout: float = 180.0, attempts: int = 1, retry_pause_time: float = 0.1, enable_cache: bool = False) -> bytes: ...
    async def download_file(self, url: str, content_type: str, destination_path: StrOrPath | None = None, download_size: int = -1, progress_callback: Callable[[int, int, int], None] | None = None, connect_timeout: float = 5.0, request_timeout: float = 180.0, attempts: int = 1, retry_pause_time: float = 1.0) -> pathlib.Path: ...
    def wrap_request(self, default_url: str, **kwargs) -> HttpRequestWrapper: ...
    def close(self) -> None: ...

class HttpRequestWrapper:
    default_request_args: dict[str, Any]
    request_args: Incomplete
    def __init__(self, client: HttpClient, default_url: str, **kwargs) -> None: ...
    async def send(self, **kwargs) -> HttpResponse: ...
    def set_method(self, method: str) -> None: ...
    def set_url(self, url: str) -> None: ...
    def set_body(self, body: str | list[Any] | dict[str, Any] | None) -> None: ...
    def add_header(self, name: str, value: str) -> None: ...
    def set_headers(self, headers: dict[str, str]) -> None: ...
    def reset(self) -> None: ...
    def last_response(self) -> HttpResponse | None: ...

class HttpResponse:
    def __init__(self, url: str, final_url: str, code: int, result: bytes, response_headers: HTTPHeaders, error: BaseException | None) -> None: ...
    def json(self) -> list[Any] | dict[str, Any]: ...
    def is_cachable(self) -> bool: ...
    def has_error(self) -> bool: ...
    def raise_for_status(self, message: str | None = None) -> None: ...
    @property
    def encoding(self) -> str: ...
    @encoding.setter
    def encoding(self, new_enc: str) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    @property
    def url(self) -> str: ...
    @property
    def final_url(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> HTTPHeaders: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def etag(self) -> str | None: ...
    @property
    def error(self) -> BaseException | None: ...

class StreamingDownload:
    server: Incomplete
    event_loop: Incomplete
    need_content_length: bool
    need_content_disposition: bool
    request_ok: bool
    dest_file: Incomplete
    filename: Incomplete
    file_hdl: BufferedWriter | None
    total_recd: int
    download_size: int
    pct_done: int
    chunk_buffer: list[bytes]
    progress_callback: Incomplete
    busy_evt: asyncio.Event
    def __init__(self, server: Server, dest_path: StrOrPath | None, download_size: int, progress_callback: Callable[[int, int, int], None] | None) -> None: ...
    def on_headers_recd(self, line: str) -> None: ...
    def on_chunk_recd(self, chunk: bytes) -> None: ...
    async def close(self) -> None: ...

def load_component(config: ConfigHelper) -> HttpClient: ...
