import asyncio
import pathlib
from ..common import APITransport as APITransport, BaseRemoteConnection as BaseRemoteConnection, KlippyState as KlippyState, RequestType as RequestType, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from ..utils import ServerError as ServerError, get_unix_peer_credentials as get_unix_peer_credentials
from .file_manager.file_manager import FileManager as FileManager
from .job_state import JobState as JobState
from .klippy_apis import KlippyAPI as KlippyAPI
from .machine import Machine as Machine
from _typeshed import Incomplete
from typing import Any, Awaitable, Callable, Coroutine

FlexCallback = Callable[..., Coroutine | None]
Subscription = dict[str, list[str] | None]
RESERVED_ENDPOINTS: Incomplete
CACHE_EXCLUSIONS: Incomplete
INIT_TIME: float
LOG_ATTEMPT_INTERVAL: Incomplete
MAX_LOG_ATTEMPTS: Incomplete
UNIX_BUFFER_LIMIT: Incomplete
SVC_INFO_KEY: str
SRC_PATH_KEY: str
PY_EXEC_KEY: str

class KlippyConnection:
    server: Incomplete
    uds_address: Incomplete
    writer: asyncio.StreamWriter | None
    connection_mutex: asyncio.Lock
    event_loop: Incomplete
    log_no_access: bool
    connection_task: asyncio.Task | None
    closing: bool
    subscription_lock: Incomplete
    init_attempts: int
    subscriptions: dict[APITransport, Subscription]
    subscription_cache: dict[str, dict[str, Any]]
    pending_requests: dict[int, KlippyRequest]
    remote_methods: dict[str, FlexCallback]
    klippy_reg_methods: list[str]
    def __init__(self, config: ConfigHelper) -> None: ...
    @property
    def klippy_apis(self) -> KlippyAPI: ...
    @property
    def state(self) -> KlippyState: ...
    @property
    def state_message(self) -> str: ...
    @property
    def klippy_info(self) -> dict[str, Any]: ...
    @property
    def missing_requirements(self) -> list[str]: ...
    @property
    def peer_credentials(self) -> dict[str, int]: ...
    @property
    def service_info(self) -> dict[str, Any]: ...
    @property
    def unit_name(self) -> str: ...
    @property
    def path(self) -> pathlib.Path: ...
    @property
    def executable(self) -> pathlib.Path: ...
    def load_saved_state(self) -> None: ...
    async def component_init(self) -> None: ...
    async def wait_connected(self) -> bool: ...
    async def wait_started(self, timeout: float = 20.0) -> bool: ...
    def register_remote_method(self, method_name: str, cb: FlexCallback, need_klippy_reg: bool = True) -> None: ...
    def register_method_from_agent(self, connection: BaseRemoteConnection, method_name: str) -> Awaitable | None: ...
    def unregister_method(self, method_name: str): ...
    def connect(self) -> Awaitable[bool]: ...
    async def open_klippy_connection(self, primary: bool = False) -> tuple[asyncio.StreamReader, asyncio.StreamWriter]: ...
    async def request(self, web_request: WebRequest) -> Any: ...
    def remove_subscription(self, conn: APITransport) -> None: ...
    def is_connected(self) -> bool: ...
    def is_ready(self) -> bool: ...
    def is_printing(self) -> bool: ...
    def get_subscription_cache(self) -> dict[str, dict[str, Any]]: ...
    async def rollover_log(self) -> None: ...
    async def close(self, wait_closed: bool = False) -> None: ...

class KlippyRequest:
    id: Incomplete
    rpc_method: Incomplete
    params: Incomplete
    def __init__(self, rpc_method: str, params: dict[str, Any]) -> None: ...
    async def wait(self, timeout: float | None = None) -> Any: ...
    def set_exception(self, exc: Exception) -> None: ...
    def set_result(self, result: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

def load_component(config: ConfigHelper) -> KlippyConnection: ...
