from ..common import APITransport as APITransport, RequestType as RequestType, UserInfo as UserInfo, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from ..utils import Sentinel as Sentinel
from .klippy_connection import KlippyConnection as Klippy
from _typeshed import Incomplete
from typing import Any, Callable, Coroutine, Mapping

Subscription = dict[str, list[Any] | None]
SubCallback = Callable[[dict[str, dict[str, Any]], float], Coroutine | None]
INFO_ENDPOINT: str
ESTOP_ENDPOINT: str
LIST_EPS_ENDPOINT: str
GC_OUTPUT_ENDPOINT: str
GCODE_ENDPOINT: str
SUBSCRIPTION_ENDPOINT: str
STATUS_ENDPOINT: str
OBJ_LIST_ENDPOINT: str
REG_METHOD_ENDPOINT: str

class KlippyAPI(APITransport):
    server: Incomplete
    klippy: Klippy
    eventloop: Incomplete
    version: Incomplete
    host_subscription: Subscription
    subscription_callbacks: list[SubCallback]
    def __init__(self, config: ConfigHelper) -> None: ...
    async def run_gcode(self, script: str, default: Any = ...) -> str: ...
    async def start_print(self, filename: str, wait_klippy_started: bool = False, user: UserInfo | None = None) -> str: ...
    async def pause_print(self, default: Sentinel | _T = ...) -> _T | str: ...
    async def resume_print(self, default: Sentinel | _T = ...) -> _T | str: ...
    async def cancel_print(self, default: Sentinel | _T = ...) -> _T | str: ...
    async def do_restart(self, gc: str, wait_klippy_started: bool = False) -> str: ...
    async def list_endpoints(self, default: Sentinel | _T = ...) -> _T | dict[str, list[str]]: ...
    async def emergency_stop(self) -> str: ...
    async def get_klippy_info(self, send_id: bool = False, default: Sentinel | _T = ...) -> _T | dict[str, Any]: ...
    async def get_object_list(self, default: Sentinel | _T = ...) -> _T | list[str]: ...
    async def query_objects(self, objects: Mapping[str, list[str] | None], default: Sentinel | _T = ...) -> _T | dict[str, Any]: ...
    async def subscribe_objects(self, objects: Mapping[str, list[str] | None], callback: SubCallback | None = None, default: Sentinel | _T = ...) -> _T | dict[str, Any]: ...
    async def subscribe_from_transport(self, objects: Mapping[str, list[str] | None], transport: APITransport, default: Sentinel | _T = ..., full_response: bool = False) -> _T | dict[str, Any]: ...
    async def subscribe_gcode_output(self) -> str: ...
    async def register_method(self, method_name: str) -> str: ...
    def send_status(self, status: dict[str, Any], eventtime: float) -> None: ...

def load_component(config: ConfigHelper) -> KlippyAPI: ...
