from ..common import RequestType as RequestType, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper, FileSourceWrapper as FileSourceWrapper
from ..utils import cansocket as cansocket, load_system_module as load_system_module, source_info as source_info, sysfs_devs as sysfs_devs
from .announcements import Announcements as Announcements
from .application import MoonrakerApp as MoonrakerApp
from .database import MoonrakerDatabase as MoonrakerDatabase
from .dbus_manager import DbusManager as DbusManager
from .file_manager.file_manager import FileManager as FileManager
from .http_client import HttpClient as HttpClient
from .klippy_connection import KlippyConnection as KlippyConnection
from .proc_stats import ProcStats as ProcStats
from .shell_command import ShellCommandFactory as SCMDComp
from _typeshed import Incomplete
from dbus_fast.aio.proxy_object import ProxyInterface as ProxyInterface
from dbus_fast.signature import Variant as Variant
from typing import Any, Awaitable, Callable

SudoReturn = Awaitable[tuple[str, bool]] | tuple[str, bool]
SudoCallback = Callable[[], SudoReturn]
CGROUP_PATH: str
SCHED_PATH: str
SYSTEMD_PATH: str
SD_CID_PATH: str
SD_CSD_PATH: str
SD_MFGRS: Incomplete
IP_FAMILIES: Incomplete
NETWORK_UPDATE_SEQUENCE: int
SERVICE_PROPERTIES: Incomplete
USB_IDS_URL: str

class Machine:
    server: Incomplete
    inside_container: bool
    moonraker_service_info: dict[str, Any]
    sudo_req_lock: Incomplete
    periph_lock: Incomplete
    system_info: dict[str, Any]
    provider_type: Incomplete
    sys_provider: BaseProvider
    validator: Incomplete
    sudo_requests: list[tuple[SudoCallback, str]]
    addr_cmd: Incomplete
    iwgetid_cmd: Incomplete
    init_evt: Incomplete
    libcam: Incomplete
    def __init__(self, config: ConfigHelper) -> None: ...
    @property
    def public_ip(self) -> str: ...
    @property
    def unit_name(self) -> str: ...
    def is_service_allowed(self, service: str) -> bool: ...
    def validation_enabled(self) -> bool: ...
    def get_system_provider(self): ...
    def is_inside_container(self): ...
    def get_provider_type(self): ...
    def get_moonraker_service_info(self): ...
    async def wait_for_init(self, timeout: float | None = None) -> None: ...
    async def component_init(self) -> None: ...
    async def validate_installation(self) -> bool: ...
    async def on_exit(self) -> None: ...
    async def do_service_action(self, action: str, service_name: str) -> None: ...
    def restart_moonraker_service(self) -> None: ...
    def get_system_info(self) -> dict[str, Any]: ...
    @property
    def sudo_password(self) -> str | None: ...
    @sudo_password.setter
    def sudo_password(self, pwd: str | None) -> None: ...
    @property
    def sudo_requested(self) -> bool: ...
    @property
    def linux_user(self) -> str: ...
    @property
    def sudo_request_messages(self) -> list[str]: ...
    def register_sudo_request(self, callback: SudoCallback, message: str) -> None: ...
    async def check_sudo_access(self, cmds: list[str] = []) -> bool: ...
    async def exec_sudo_command(self, command: str, tries: int = 1, timeout: float = 2.0) -> str: ...
    async def get_public_network(self) -> dict[str, Any]: ...
    def log_service_info(self, svc_info: dict[str, Any]) -> None: ...
    async def update_usb_ids(self, force: bool = False) -> None: ...
    async def detect_serial_devices(self) -> list[dict[str, Any]]: ...
    async def detect_usb_devices(self) -> list[dict[str, Any]]: ...
    async def query_can_uuids(self, interface: str) -> list[dict[str, Any]]: ...
    async def detect_video_devices(self) -> dict[str, list[dict[str, Any]]]: ...
    def get_libcamera_devices(self) -> list[dict[str, Any]]: ...

class BaseProvider:
    server: Incomplete
    shutdown_action: Incomplete
    available_services: dict[str, dict[str, str]]
    shell_cmd: SCMDComp
    def __init__(self, config: ConfigHelper) -> None: ...
    async def initialize(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def reboot(self) -> None: ...
    async def do_service_action(self, action: str, service_name: str) -> None: ...
    async def check_virt_status(self) -> dict[str, Any]: ...
    def is_service_available(self, service: str) -> bool: ...
    def get_available_services(self) -> dict[str, dict[str, str]]: ...
    async def extract_service_info(self, service_name: str, pid: int, properties: list[str] | None = None, raw: bool = False) -> dict[str, Any]: ...

class SystemdCliProvider(BaseProvider):
    svc_cmd: Incomplete
    async def initialize(self) -> None: ...
    async def do_service_action(self, action: str, service_name: str) -> None: ...
    async def check_virt_status(self) -> dict[str, Any]: ...
    async def extract_service_info(self, service_name: str, pid: int, properties: list[str] | None = None, raw: bool = False) -> dict[str, Any]: ...

class SystemdDbusProvider(BaseProvider):
    dbus_mgr: DbusManager
    login_mgr: ProxyInterface | None
    props: list[tuple[ProxyInterface, Callable]]
    def __init__(self, config: ConfigHelper) -> None: ...
    systemd_mgr: Incomplete
    async def initialize(self) -> None: ...
    async def reboot(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def do_service_action(self, action: str, service_name: str) -> None: ...
    async def check_virt_status(self) -> dict[str, Any]: ...
    async def extract_service_info(self, service_name: str, pid: int, properties: list[str] | None = None, raw: bool = False) -> dict[str, Any]: ...

class SupervisordCliProvider(BaseProvider):
    spv_conf: str
    def __init__(self, config: ConfigHelper) -> None: ...
    svc_cmd: Incomplete
    async def initialize(self) -> None: ...
    async def do_service_action(self, action: str, service_name: str) -> None: ...
    async def extract_service_info(self, service_name: str, pid: int, properties: list[str] | None = None, raw: bool = False) -> dict[str, Any]: ...

INSTALL_VERSION: int
SERVICE_VERSION: int
SYSTEMD_UNIT: str
TEMPLATE_NAME: str

class ValidationError(Exception): ...

class InstallValidator:
    server: Incomplete
    config: Incomplete
    force_validation: Incomplete
    sc_enabled: Incomplete
    cc_enabled: Incomplete
    data_path: Incomplete
    data_path_valid: bool
    announcement_id: str
    validation_enabled: bool
    def __init__(self, config: ConfigHelper) -> None: ...
    async def validation_init(self) -> None: ...
    async def perform_validation(self) -> bool: ...
    async def remove_announcement(self) -> None: ...

def load_component(config: ConfigHelper) -> Machine: ...
