import pathlib
from ..confighelper import ConfigHelper as ConfigHelper
from _typeshed import Incomplete
from typing import Any

class Secrets:
    type: str
    values: dict[str, Any]
    secrets_file: Incomplete
    def __init__(self, config: ConfigHelper) -> None: ...
    def get_secrets_file(self) -> pathlib.Path: ...
    def get_type(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...

def load_component(config: ConfigHelper) -> Secrets: ...
