import asyncio
from ..common import BaseRemoteConnection as BaseRemoteConnection, RequestType as RequestType, TransportType as TransportType, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from ..server import Server as Server
from ..utils import IPAddress as IPAddress, ServerError as ServerError, parse_ip_address as parse_ip_address
from .application import MoonrakerApp as MoonrakerApp
from .authorization import Authorization as Authorization
from .extensions import ExtensionManager as ExtensionManager
from _typeshed import Incomplete
from tornado.websocket import WebSocketHandler
from typing import Any, Callable, Coroutine

ConvType = str | bool | float | int
ArgVal = None | int | float | bool | str
RPCCallback = Callable[..., Coroutine]
AuthComp = Authorization | None
CLIENT_TYPES: Incomplete

class WebsocketManager:
    server: Incomplete
    clients: dict[int, BaseRemoteConnection]
    bridge_connections: dict[int, BridgeSocket]
    closed_event: asyncio.Event | None
    def __init__(self, config: ConfigHelper) -> None: ...
    def register_notification(self, event_name: str, notify_name: str | None = None, event_type: str | None = None) -> None: ...
    def has_socket(self, ws_id: int) -> bool: ...
    def get_client(self, uid: int) -> BaseRemoteConnection | None: ...
    def get_client_ws(self, ws_id: int) -> WebSocket | None: ...
    def get_clients_by_type(self, client_type: str) -> list[BaseRemoteConnection]: ...
    def get_clients_by_name(self, name: str) -> list[BaseRemoteConnection]: ...
    def get_unidentified_clients(self) -> list[BaseRemoteConnection]: ...
    def add_client(self, sc: BaseRemoteConnection) -> None: ...
    def remove_client(self, sc: BaseRemoteConnection) -> None: ...
    def add_bridge_connection(self, bc: BridgeSocket) -> None: ...
    def remove_bridge_connection(self, bc: BridgeSocket) -> None: ...
    def notify_clients(self, name: str, data: list | tuple = [], mask: list[int] = []) -> None: ...
    def get_count(self) -> int: ...
    async def close(self) -> None: ...

class WebSocket(WebSocketHandler, BaseRemoteConnection):
    connection_count: int
    last_pong_time: float
    cors_allowed: bool
    def initialize(self) -> None: ...
    @property
    def ip_addr(self) -> IPAddress | None: ...
    @property
    def hostname(self) -> str: ...
    def get_current_user(self) -> Any: ...
    def open(self, *args, **kwargs) -> None: ...
    def on_message(self, message: bytes | str) -> None: ...
    def on_pong(self, data: bytes) -> None: ...
    is_closed: bool
    message_buf: Incomplete
    pending_responses: Incomplete
    def on_close(self) -> None: ...
    async def write_to_socket(self, message: bytes | str) -> None: ...
    def check_origin(self, origin: str) -> bool: ...
    def on_user_logout(self, user: str) -> bool: ...
    async def prepare(self) -> None: ...
    def close_socket(self, code: int, reason: str) -> None: ...

class BridgeSocket(WebSocketHandler):
    server: Server
    wsm: WebsocketManager
    eventloop: Incomplete
    uid: Incomplete
    last_pong_time: float
    is_closed: bool
    klippy_writer: asyncio.StreamWriter | None
    klippy_write_buf: list[bytes]
    klippy_queue_busy: bool
    cors_allowed: bool
    def initialize(self) -> None: ...
    @property
    def ip_addr(self) -> IPAddress | None: ...
    @property
    def hostname(self) -> str: ...
    def open(self, *args, **kwargs) -> None: ...
    def on_message(self, message: bytes | str) -> None: ...
    def on_pong(self, data: bytes) -> None: ...
    def on_close(self) -> None: ...
    def check_origin(self, origin: str) -> bool: ...
    current_user: Incomplete
    async def prepare(self) -> None: ...
    def close_socket(self, code: int, reason: str) -> None: ...

def load_component(config: ConfigHelper) -> WebsocketManager: ...
