import asyncio
from ..common import RequestType as RequestType, WebRequest as WebRequest
from ..confighelper import ConfigHelper as ConfigHelper
from ..utils import async_serial as async_serial
from .http_client import HttpClient as HttpClient
from _typeshed import Incomplete
from typing import Any, Coroutine

class OnOff:
    on: str
    off: str

class Strip:
    server: Incomplete
    request_mutex: Incomplete
    name: Incomplete
    initial_preset: int
    initial_red: float
    initial_green: float
    initial_blue: float
    initial_white: float
    chain_count: int
    onoff: Incomplete
    preset: Incomplete
    def __init__(self, name: str, config: ConfigHelper) -> None: ...
    def get_strip_info(self) -> dict[str, Any]: ...
    async def initialize(self) -> None: ...
    async def send_wled_command_impl(self, state: dict[str, Any]) -> dict[str, Any]: ...
    def close(self) -> Coroutine | None: ...
    send_full_chain_data: bool
    brightness: int
    intensity: int
    speed: int
    async def wled_on(self, preset: int) -> None: ...
    async def wled_off(self) -> None: ...
    async def wled_control(self, brightness: int, intensity: int, speed: int) -> None: ...
    async def set_wled(self, red: float, green: float, blue: float, white: float, index: int | None, transmit: bool) -> None: ...

class StripHttp(Strip):
    url: Incomplete
    timeout: float
    client: HttpClient
    def __init__(self, name: str, config: ConfigHelper) -> None: ...
    async def send_wled_command_impl(self, state: dict[str, Any]) -> dict[str, Any]: ...

class StripSerial(Strip):
    serial: Incomplete
    enabled: bool
    serial_task: asyncio.Task | None
    pending_response: asyncio.Future | None
    def __init__(self, name: str, config: ConfigHelper) -> None: ...
    async def run_serial(self) -> None: ...
    async def initialize(self) -> None: ...
    async def send_wled_command_impl(self, state: dict[str, Any]) -> dict[str, Any]: ...
    async def close(self) -> None: ...

class WLED:
    server: Incomplete
    strips: dict[str, Strip]
    def __init__(self, config: ConfigHelper) -> None: ...
    async def component_init(self) -> None: ...
    async def wled_on(self, strip: str, preset: int) -> None: ...
    async def set_wled_state(self, strip: str, state: str | None = None, preset: int = -1, brightness: int = -1, intensity: int = -1, speed: int = -1) -> None: ...
    async def set_wled(self, strip: str, red: float = 0.0, green: float = 0.0, blue: float = 0.0, white: float = 0.0, index: int | None = None, transmit: int = 1) -> None: ...
    async def close(self) -> None: ...

def load_component(config: ConfigHelper) -> WLED: ...
