import dataclasses
import time
from .components.authorization import Authorization as Authorization
from .components.database import DBProviderWrapper as DBProviderWrapper
from .components.history import History as History
from .components.websockets import WebsocketManager as WebsocketManager
from .server import Server as Server
from .utils import IPAddress as IPAddress, Sentinel as Sentinel
from .utils.exceptions import AgentError as AgentError, ServerError as ServerError
from _typeshed import Incomplete
from abc import ABCMeta, abstractmethod
from asyncio import Future
from enum import Enum, Flag
from typing import Any, Awaitable, Callable, Coroutine, Generic

ConvType = str | bool | float | int
ArgVal = None | int | float | bool | str
RPCCallback = Callable[..., Coroutine]
AuthComp = Authorization | None
ENDPOINT_PREFIXES: Incomplete

class ExtendedFlag(Flag):
    @classmethod
    def from_string(cls, flag_name: str) -> _F: ...
    @classmethod
    def from_string_list(cls, flag_list: list[str]) -> _F: ...
    @classmethod
    def all(cls) -> _F: ...

class RequestType(ExtendedFlag):
    GET = ...
    POST = ...
    DELETE = ...

class TransportType(ExtendedFlag):
    HTTP = ...
    WEBSOCKET = ...
    MQTT = ...
    INTERNAL = ...

class ExtendedEnum(Enum):
    @classmethod
    def from_string(cls, enum_name: str): ...

class JobEvent(ExtendedEnum):
    STANDBY = 1
    STARTED = 2
    PAUSED = 3
    RESUMED = 4
    COMPLETE = 5
    ERROR = 6
    CANCELLED = 7
    @property
    def finished(self) -> bool: ...
    @property
    def aborted(self) -> bool: ...
    @property
    def is_printing(self) -> bool: ...

class KlippyState(ExtendedEnum):
    DISCONNECTED = 1
    STARTUP = 2
    READY = 3
    ERROR = 4
    SHUTDOWN = 5
    @classmethod
    def from_string(cls, enum_name: str, msg: str = ''): ...
    def set_message(self, msg: str) -> None: ...
    @property
    def message(self) -> str: ...
    def startup_complete(self) -> bool: ...

class RenderableTemplate(metaclass=ABCMeta):
    @abstractmethod
    def render(self, context: dict[str, Any] = {}) -> str: ...
    @abstractmethod
    async def render_async(self, context: dict[str, Any] = {}) -> str: ...

@dataclasses.dataclass
class UserInfo:
    username: str
    password: str
    created_on: float = dataclasses.field(default_factory=time.time)
    salt: str = ...
    source: str = ...
    jwt_secret: str | None = ...
    jwk_id: str | None = ...
    groups: list[str] = dataclasses.field(default_factory=Incomplete)
    def as_tuple(self) -> tuple[Any, ...]: ...
    def as_dict(self) -> dict[str, Any]: ...

@dataclasses.dataclass(frozen=True)
class APIDefinition:
    endpoint: str
    http_path: str
    rpc_methods: list[str]
    request_types: RequestType
    transports: TransportType
    callback: Callable[[WebRequest], Coroutine]
    auth_required: bool
    def request(self, args: dict[str, Any], request_type: RequestType, transport: APITransport | None = None, ip_addr: IPAddress | None = None, user: UserInfo | None = None) -> Coroutine: ...
    @property
    def need_object_parser(self) -> bool: ...
    def rpc_items(self) -> zip[tuple[RequestType, str]]: ...
    @classmethod
    def create(cls, endpoint: str, request_types: list[str] | RequestType, callback: Callable[[WebRequest], Coroutine], transports: list[str] | TransportType = ..., auth_required: bool = True, is_remote: bool = False) -> APIDefinition: ...
    @classmethod
    def pop_cached_def(cls, endpoint: str) -> APIDefinition | None: ...
    @classmethod
    def get_cache(cls) -> dict[str, APIDefinition]: ...
    @classmethod
    def reset_cache(cls) -> None: ...

class APITransport:
    @property
    def transport_type(self) -> TransportType: ...
    @property
    def user_info(self) -> UserInfo | None: ...
    @property
    def ip_addr(self) -> IPAddress | None: ...
    def screen_rpc_request(self, api_def: APIDefinition, req_type: RequestType, args: dict[str, Any]) -> None: ...
    def send_status(self, status: dict[str, Any], eventtime: float) -> None: ...

class BaseRemoteConnection(APITransport):
    server: Incomplete
    eventloop: Incomplete
    wsm: WebsocketManager
    rpc: JsonRPC
    is_closed: bool
    queue_busy: bool
    pending_responses: dict[int, Future]
    message_buf: list[bytes | str]
    def on_create(self, server: Server) -> None: ...
    @property
    def user_info(self) -> UserInfo | None: ...
    @user_info.setter
    def user_info(self, uinfo: UserInfo) -> None: ...
    @property
    def need_auth(self) -> bool: ...
    @property
    def uid(self) -> int: ...
    @property
    def hostname(self) -> str: ...
    @property
    def start_time(self) -> float: ...
    @property
    def identified(self) -> bool: ...
    @property
    def client_data(self) -> dict[str, str]: ...
    @client_data.setter
    def client_data(self, data: dict[str, str]) -> None: ...
    @property
    def transport_type(self) -> TransportType: ...
    def screen_rpc_request(self, api_def: APIDefinition, req_type: RequestType, args: dict[str, Any]) -> None: ...
    def queue_message(self, message: bytes | str | dict[str, Any]): ...
    def authenticate(self, token: str | None = None, api_key: str | None = None) -> None: ...
    def check_authenticated(self, api_def: APIDefinition) -> None: ...
    def on_user_logout(self, user: str) -> bool: ...
    async def write_to_socket(self, message: bytes | str) -> None: ...
    def send_status(self, status: dict[str, Any], eventtime: float) -> None: ...
    def call_method_with_response(self, method: str, params: list | dict[str, Any] | None = None) -> Awaitable: ...
    def call_method(self, method: str, params: list | dict[str, Any] | None = None) -> None: ...
    def send_notification(self, name: str, data: list) -> None: ...
    def resolve_pending_response(self, response_id: int, result: Any) -> bool: ...
    def close_socket(self, code: int, reason: str) -> None: ...

class WebRequest:
    endpoint: Incomplete
    args: Incomplete
    transport: Incomplete
    request_type: Incomplete
    ip_addr: IPAddress | None
    current_user: Incomplete
    def __init__(self, endpoint: str, args: dict[str, Any], request_type: RequestType = ..., transport: APITransport | None = None, ip_addr: IPAddress | None = None, user: UserInfo | None = None) -> None: ...
    def get_endpoint(self) -> str: ...
    def get_request_type(self) -> RequestType: ...
    def get_action(self) -> str: ...
    def get_args(self) -> dict[str, Any]: ...
    def get_subscribable(self) -> APITransport | None: ...
    def get_client_connection(self) -> BaseRemoteConnection | None: ...
    def get_ip_address(self) -> IPAddress | None: ...
    def get_current_user(self) -> UserInfo | None: ...
    def get(self, key: str, default: Sentinel | _T = ...) -> _T | Any: ...
    def get_str(self, key: str, default: Sentinel | _T = ...) -> str | _T: ...
    def get_int(self, key: str, default: Sentinel | _T = ...) -> int | _T: ...
    def get_float(self, key: str, default: Sentinel | _T = ...) -> float | _T: ...
    def get_boolean(self, key: str, default: Sentinel | _T = ...) -> bool | _T: ...
    def get_list(self, key: str, default: Sentinel | _T = ..., sep: str = ',', count: int | None = None) -> _T | list[str]: ...
    def get_request_body(self) -> bytes | str: ...

class JsonRPC:
    methods: dict[str, tuple[RequestType, APIDefinition]]
    sanitize_response: bool
    verbose: Incomplete
    def __init__(self, server: Server) -> None: ...
    def register_method(self, name: str, request_type: RequestType, api_definition: APIDefinition) -> None: ...
    def get_method(self, name: str) -> tuple[RequestType, APIDefinition] | None: ...
    def remove_method(self, name: str) -> None: ...
    async def dispatch(self, data: str | bytes, transport: APITransport) -> bytes | None: ...
    async def process_object(self, obj: dict[str, Any], transport: APITransport) -> dict[str, Any] | None: ...
    def process_response(self, obj: dict[str, Any], conn: APITransport) -> None: ...
    async def execute_method(self, method_name: str, request_type: RequestType, api_definition: APIDefinition, req_id: int | None, transport: APITransport, params: dict[str, Any]) -> dict[str, Any] | None: ...
    def build_result(self, result: Any, req_id: int) -> dict[str, Any]: ...
    def build_error(self, code: int, msg: str, req_id: int | None = None, exc: Exception | None = None, method_name: str = '') -> dict[str, Any]: ...

class FieldTracker(Generic[_T]):
    history: History
    tracked_value: Incomplete
    exclude_paused: Incomplete
    reset_callback: Callable[[], _T] | None
    def __init__(self, value: _T = None, reset_callback: Callable[[], _T] | None = None, exclude_paused: bool = False) -> None: ...
    def set_reset_callback(self, cb: Callable[[], _T] | None) -> None: ...
    def set_exclude_paused(self, exclude: bool) -> None: ...
    def reset(self) -> None: ...
    def update(self, value: _T) -> None: ...
    def get_tracked_value(self) -> _T: ...
    def has_totals(self) -> bool: ...
    @classmethod
    def class_init(cls, history: History) -> None: ...

class BasicTracker(FieldTracker[Any]):
    def __init__(self, value: Any = None, reset_callback: Callable[[], Any] | None = None, exclude_paused: bool = False) -> None: ...
    tracked_value: Incomplete
    def reset(self) -> None: ...
    def update(self, value: Any) -> None: ...
    def has_totals(self) -> bool: ...

class DeltaTracker(FieldTracker[int | float]):
    last_value: float | int | None
    def __init__(self, value: int | float = 0, reset_callback: Callable[[], float | int] | None = None, exclude_paused: bool = False) -> None: ...
    tracked_value: int
    def reset(self) -> None: ...
    def update(self, value: int | float) -> None: ...
    def has_totals(self) -> bool: ...

class CumulativeTracker(FieldTracker[int | float]):
    def __init__(self, value: int | float = 0, reset_callback: Callable[[], float | int] | None = None, exclude_paused: bool = False) -> None: ...
    tracked_value: Incomplete
    def reset(self) -> None: ...
    def update(self, value: int | float) -> None: ...
    def has_totals(self) -> bool: ...

class AveragingTracker(CumulativeTracker):
    count: int
    def __init__(self, value: int | float = 0, reset_callback: Callable[[], float | int] | None = None, exclude_paused: bool = False) -> None: ...
    def reset(self) -> None: ...
    tracked_value: Incomplete
    def update(self, value: int | float) -> None: ...

class MaximumTracker(CumulativeTracker):
    initialized: bool
    def __init__(self, value: int | float = 0, reset_callback: Callable[[], float | int] | None = None, exclude_paused: bool = False) -> None: ...
    tracked_value: Incomplete
    def reset(self) -> None: ...
    def update(self, value: float | int) -> None: ...

class MinimumTracker(CumulativeTracker):
    initialized: bool
    def __init__(self, value: int | float = 0, reset_callback: Callable[[], float | int] | None = None, exclude_paused: bool = False) -> None: ...
    tracked_value: Incomplete
    def reset(self) -> None: ...
    def update(self, value: float | int) -> None: ...

class CollectionTracker(FieldTracker[list[Any]]):
    MAX_SIZE: int
    def __init__(self, value: list[Any] = [], reset_callback: Callable[[], list[Any]] | None = None, exclude_paused: bool = False) -> None: ...
    tracked_value: Incomplete
    def reset(self) -> None: ...
    def update(self, value: Any) -> None: ...
    def has_totals(self) -> bool: ...

class TrackingStrategy(ExtendedEnum):
    BASIC = 1
    DELTA = 2
    ACCUMULATE = 3
    AVERAGE = 4
    MAXIMUM = 5
    MINIMUM = 6
    COLLECT = 7
    def get_tracker(self, **kwargs) -> FieldTracker: ...

class HistoryFieldData:
    def __init__(self, field_name: str, provider: str, desc: str, strategy: str, units: str | None = None, reset_callback: Callable[[], _T] | None = None, exclude_paused: bool = False, report_total: bool = False, report_maximum: bool = False, precision: int | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def provider(self) -> str: ...
    @property
    def tracker(self) -> FieldTracker: ...
    def __eq__(self, value: object) -> bool: ...
    def get_configuration(self) -> dict[str, Any]: ...
    def as_dict(self) -> dict[str, Any]: ...
    def has_totals(self) -> bool: ...
    def get_totals(self, last_totals: list[dict[str, Any]], reset: bool = False) -> dict[str, Any]: ...

class SqlTableDefType(type):
    def __new__(metacls, clsname: str, bases: tuple[type, ...], cls_attrs: dict[str, Any]): ...

class SqlTableDefinition(metaclass=SqlTableDefType):
    name: str
    version: int
    prototype: str
    def __init__(self) -> None: ...
    def migrate(self, last_version: int, db_provider: DBProviderWrapper) -> None: ...
