import hashlib
import pathlib
from .common import RenderableTemplate as RenderableTemplate
from .components.gpio import GpioEvent as GpioEvent, GpioEventCallback as GpioEventCallback, GpioFactory as GpioFactory, GpioOutputPin as GpioOutputPin
from .components.template import TemplateFactory as TemplateFactory
from .server import Server as Server
from .utils import Sentinel as Sentinel
from _typeshed import Incomplete
from typing import Any, Awaitable, IO

ConfigVal = None | int | float | bool | str | dict | list
DOCS_URL: str
CFG_ERROR_KEY: str

class ConfigError(Exception): ...

class ConfigHelper:
    error = ConfigError
    server: Incomplete
    source: Incomplete
    config: Incomplete
    section: Incomplete
    fallback_section: str | None
    parsed: Incomplete
    sections: Incomplete
    has_section: Incomplete
    def __init__(self, server: Server, config_source: ConfigSourceWrapper, section: str, parsed: dict[str, dict[str, ConfigVal]], fallback_section: str | None = None) -> None: ...
    def get_server(self) -> Server: ...
    def get_source(self) -> ConfigSourceWrapper: ...
    def __getitem__(self, key: str) -> ConfigHelper: ...
    def __contains__(self, key: str) -> bool: ...
    def has_option(self, option: str) -> bool: ...
    def set_option(self, option: str, value: str) -> None: ...
    def get_name(self) -> str: ...
    def get_file(self) -> pathlib.Path | None: ...
    def get_options(self) -> dict[str, str]: ...
    def get_hash(self) -> hashlib._Hash: ...
    def get_prefix_sections(self, prefix: str) -> list[str]: ...
    def getsection(self, section: str, fallback: str | None = None) -> ConfigHelper: ...
    def get(self, option: str, default: Sentinel | _T = ..., deprecate: bool = False) -> str | _T: ...
    def getint(self, option: str, default: Sentinel | _T = ..., above: int | None = None, below: int | None = None, minval: int | None = None, maxval: int | None = None, deprecate: bool = False) -> int | _T: ...
    def getboolean(self, option: str, default: Sentinel | _T = ..., deprecate: bool = False) -> bool | _T: ...
    def getfloat(self, option: str, default: Sentinel | _T = ..., above: float | None = None, below: float | None = None, minval: float | None = None, maxval: float | None = None, deprecate: bool = False) -> float | _T: ...
    def getchoice(self, option: str, choices: dict[str, _T] | list[_T], default_key: Sentinel | str = ..., force_lowercase: bool = False, deprecate: bool = False) -> _T: ...
    def getlists(self, option: str, default: Sentinel | _T = ..., list_type: type = ..., separators: tuple[str | None, ...] = ('\n',), count: tuple[int | None, ...] | None = None, deprecate: bool = False) -> list[Any] | _T: ...
    def getlist(self, option: str, default: Sentinel | _T = ..., separator: str | None = '\n', count: int | None = None, deprecate: bool = False) -> list[str] | _T: ...
    def getintlist(self, option: str, default: Sentinel | _T = ..., separator: str | None = '\n', count: int | None = None, deprecate: bool = False) -> list[int] | _T: ...
    def getfloatlist(self, option: str, default: Sentinel | _T = ..., separator: str | None = '\n', count: int | None = None, deprecate: bool = False) -> list[float] | _T: ...
    def getdict(self, option: str, default: Sentinel | _T = ..., separators: tuple[str | None, str | None] = ('\n', '='), dict_type: type = ..., allow_empty_fields: bool = False, deprecate: bool = False) -> dict[str, Any] | _T: ...
    def getgpioout(self, option: str, default: Sentinel | _T = ..., initial_value: int = 0, deprecate: bool = False) -> GpioOutputPin | _T: ...
    def getgpioevent(self, option: str, event_callback: GpioEventCallback, default: Sentinel | _T = ..., deprecate: bool = False) -> GpioEvent | _T: ...
    def gettemplate(self, option: str, default: Sentinel | _T = ..., is_async: bool = False, deprecate: bool = False) -> RenderableTemplate | _T: ...
    def load_template(self, option: str, default: Sentinel | str = ..., is_async: bool = False, deprecate: bool = False) -> RenderableTemplate: ...
    def getpath(self, option: str, default: Sentinel | _T = ..., deprecate: bool = False) -> pathlib.Path | _T: ...
    def read_supplemental_dict(self, obj: dict[str, Any]) -> ConfigHelper: ...
    def read_supplemental_config(self, file_name: str) -> ConfigHelper: ...
    def write_config(self, file_obj: IO[str]) -> None: ...
    def get_parsed_config(self) -> dict[str, dict[str, ConfigVal]]: ...
    def get_orig_config(self) -> dict[str, dict[str, str]]: ...
    def get_file_sections(self) -> dict[str, list[str]]: ...
    def get_config_files(self) -> list[str]: ...
    def validate_config(self) -> None: ...
    def create_backup(self) -> None: ...

class ConfigSourceWrapper:
    config: Incomplete
    def __init__(self) -> None: ...
    def get_parser(self): ...
    def as_dict(self) -> dict[str, dict[str, str]]: ...
    def write_to_string(self) -> str: ...
    def get_files(self) -> list[pathlib.Path]: ...
    def set_option(self, section: str, option: str, value: str) -> None: ...
    def remove_option(self, section: str, option: str) -> None: ...
    def add_section(self, section: str) -> None: ...
    def remove_section(self, section: str) -> None: ...
    def get_file_sections(self) -> dict[str, list[str]]: ...
    def find_config_file(self, section: str, option: str | None = None) -> pathlib.Path | None: ...

class DictSourceWrapper(ConfigSourceWrapper):
    def __init__(self) -> None: ...
    def read_dict(self, cfg: dict[str, Any]) -> None: ...

class FileSourceWrapper(ConfigSourceWrapper):
    section_r: Incomplete
    server: Incomplete
    files: list[pathlib.Path]
    raw_config_data: list[str]
    updates_pending: set[int]
    file_section_map: dict[str, list[int]]
    file_option_map: dict[tuple[str, str], list[int]]
    save_lock: Incomplete
    backup: dict[str, Any]
    def __init__(self, server: Server) -> None: ...
    def get_files(self) -> list[pathlib.Path]: ...
    def is_in_transaction(self) -> bool: ...
    def backup_source(self) -> None: ...
    def set_option(self, section: str, option: str, value: str) -> None: ...
    def remove_option(self, section: str, option: str) -> None: ...
    def add_section(self, section: str) -> None: ...
    def remove_section(self, section: str) -> None: ...
    def save(self) -> Awaitable[bool]: ...
    def cancel(self) -> None: ...
    def revert(self) -> Awaitable[bool]: ...
    def write_config(self, dest_folder: str | pathlib.Path) -> Awaitable[None]: ...
    def get_file_sections(self) -> dict[str, list[str]]: ...
    def find_config_file(self, section: str, option: str | None = None) -> pathlib.Path | None: ...
    def read_file(self, main_conf: pathlib.Path) -> None: ...

def get_configuration(server: Server, app_args: dict[str, Any]) -> ConfigHelper: ...
def find_config_backup(cfg_path: str) -> str | None: ...
