import asyncio
import socket
from _typeshed import Incomplete
from asyncio import AbstractEventLoop
from typing import Awaitable, Callable

FlexCallback = Callable[..., Awaitable | None]
TimerCallback = Callable[[float], float | Awaitable[float]]

class EventLoop:
    UVLOOP_ENABLED: Incomplete
    TimeoutError = asyncio.TimeoutError
    def __init__(self) -> None: ...
    @property
    def asyncio_loop(self) -> AbstractEventLoop: ...
    aioloop: Incomplete
    bg_tasks: set[asyncio.Task]
    add_signal_handler: Incomplete
    remove_signal_handler: Incomplete
    add_reader: Incomplete
    add_writer: Incomplete
    remove_reader: Incomplete
    remove_writer: Incomplete
    get_loop_time: Incomplete
    create_future: Incomplete
    call_at: Incomplete
    set_debug: Incomplete
    is_running: Incomplete
    def reset(self) -> None: ...
    def create_task(self, coro: asyncio._CoroutineLike[_T]) -> asyncio.Task[_T]: ...
    def register_callback(self, callback: FlexCallback, *args, **kwargs) -> None: ...
    def delay_callback(self, delay: float, callback: FlexCallback, *args, **kwargs) -> asyncio.TimerHandle: ...
    def register_timer(self, callback: TimerCallback): ...
    def run_in_thread(self, callback: Callable[..., _T], *args) -> Awaitable[_T]: ...
    async def create_socket_connection(self, address: tuple[str, int], timeout: float | None = None) -> socket.socket: ...
    def close(self) -> None: ...

class FlexTimer:
    eventloop: Incomplete
    callback: Incomplete
    timer_handle: asyncio.TimerHandle | None
    timer_task: asyncio.Task | None
    running: bool
    def __init__(self, eventloop: EventLoop, callback: TimerCallback) -> None: ...
    def in_callback(self) -> bool: ...
    def start(self, delay: float = 0.0): ...
    def stop(self) -> None: ...
    async def wait_timer_done(self) -> None: ...
    def is_running(self) -> bool: ...
