import logging
import logging.handlers
from .common import RequestType as RequestType, WebRequest as WebRequest
from .components.klippy_connection import KlippyConnection as KlippyConnection
from .server import Server as Server
from _typeshed import Incomplete
from typing import Any, Awaitable

class StructuredFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str: ...

class LocalQueueHandler(logging.handlers.QueueHandler):
    def emit(self, record: logging.LogRecord) -> None: ...

class MoonrakerLoggingHandler(logging.handlers.TimedRotatingFileHandler):
    app_args: Incomplete
    rollover_info: dict[str, str]
    def __init__(self, app_args: dict[str, Any], **kwargs) -> None: ...
    def set_rollover_info(self, name: str, item: str) -> None: ...
    def doRollover(self) -> None: ...
    def write_header(self) -> None: ...

class LogManager:
    file_hdlr: MoonrakerLoggingHandler | None
    listener: logging.handlers.QueueListener | None
    def __init__(self, app_args: dict[str, Any], startup_warnings: list[str]) -> None: ...
    server: Incomplete
    def set_server(self, server: Server) -> None: ...
    def set_rollover_info(self, name: str, item: str) -> None: ...
    def rollover_log(self) -> Awaitable[None]: ...
    def stop_logging(self) -> None: ...
