import asyncio
from . import confighelper as confighelper
from .common import RequestType as RequestType, WebRequest as WebRequest
from .components.application import MoonrakerApp as MoonrakerApp
from .components.extensions import ExtensionManager as ExtensionManager
from .components.file_manager.file_manager import FileManager as FileManager
from .components.klippy_connection import KlippyConnection as KlippyConnection
from .components.machine import Machine as Machine
from .components.websockets import WebsocketManager as WebsocketManager
from .eventloop import EventLoop as EventLoop
from .loghelper import LogManager as LogManager
from .utils import Sentinel as Sentinel, ServerError as ServerError, get_software_info as get_software_info, json_wrapper as json_wrapper, pip_utils as pip_utils, source_info as source_info
from _typeshed import Incomplete
from typing import Any, Callable, Coroutine

FlexCallback = Callable[..., Coroutine | None]
API_VERSION: Incomplete
SERVER_COMPONENTS: Incomplete
CORE_COMPONENTS: Incomplete

class Server:
    error = ServerError
    config_error = confighelper.ConfigError
    event_loop: Incomplete
    log_manager: Incomplete
    app_args: Incomplete
    events: dict[str, list[FlexCallback]]
    components: dict[str, Any]
    failed_components: list[str]
    warnings: dict[str, str]
    config: Incomplete
    host: str
    port: int
    ssl_port: int
    exit_reason: str
    server_running: bool
    app_running_evt: Incomplete
    pip_recovery_attempted: bool
    debug: Incomplete
    klippy_connection: KlippyConnection
    moonraker_app: MoonrakerApp
    register_endpoint: Incomplete
    register_debug_endpoint: Incomplete
    register_static_file_handler: Incomplete
    register_upload_handler: Incomplete
    websocket_manager: WebsocketManager
    def __init__(self, args: dict[str, Any], log_manager: LogManager, event_loop: EventLoop) -> None: ...
    def get_app_args(self) -> dict[str, Any]: ...
    def get_app_arg(self, key: str, default=...) -> Any: ...
    def get_event_loop(self) -> EventLoop: ...
    def get_api_version(self) -> tuple[int, int, int]: ...
    def get_warnings(self) -> list[str]: ...
    def is_running(self) -> bool: ...
    def is_configured(self) -> bool: ...
    def is_debug_enabled(self) -> bool: ...
    def is_verbose_enabled(self) -> bool: ...
    async def server_init(self, start_server: bool = True) -> None: ...
    async def start_server(self, connect_to_klippy: bool = True) -> None: ...
    async def run_until_exit(self) -> None: ...
    def add_log_rollover_item(self, name: str, item: str, log: bool = True) -> None: ...
    def add_warning(self, warning: str, warn_id: str | None = None, log: bool = True, exc_info: BaseException | None = None) -> str: ...
    def remove_warning(self, warn_id: str) -> None: ...
    def load_components(self) -> None: ...
    def load_component(self, config: confighelper.ConfigHelper, component_name: str, default: _T = ...) -> _T | Any: ...
    def try_pip_recovery(self, missing_module: str) -> bool: ...
    def lookup_component(self, component_name: str, default: _T = ...) -> _T | Any: ...
    def set_failed_component(self, component_name: str) -> None: ...
    def register_component(self, component_name: str, component: Any) -> None: ...
    def register_notification(self, event_name: str, notify_name: str | None = None) -> None: ...
    def register_event_handler(self, event: str, callback: FlexCallback) -> None: ...
    def send_event(self, event: str, *args) -> asyncio.Future: ...
    def register_remote_method(self, method_name: str, cb: FlexCallback) -> None: ...
    def get_host_info(self) -> dict[str, Any]: ...
    def get_klippy_info(self) -> dict[str, Any]: ...
    def restart(self, delay: float | None = None) -> None: ...

async def launch_server(log_manager: LogManager, app_args: dict[str, Any]) -> int | None: ...
def main(from_package: bool = True) -> None: ...
