from ...confighelper import ConfigHelper as ConfigHelper
from ...utils import ServerError as ServerError, pretty_print_time as pretty_print_time
from .update_manager import CommandHelper as CommandHelper
from _typeshed import Incomplete
from typing import Any, Coroutine

class BaseDeploy:
    cmd_helper: CommandHelper
    name: Incomplete
    prefix: Incomplete
    server: Incomplete
    refresh_interval: Incomplete
    cfg_hash: Incomplete
    def __init__(self, config: ConfigHelper, name: str | None = None, prefix: str = '', cfg_hash: str | None = None) -> None: ...
    @staticmethod
    def parse_name(config: ConfigHelper) -> str: ...
    @staticmethod
    def set_command_helper(cmd_helper: CommandHelper) -> None: ...
    last_refresh_time: float
    last_cfg_hash: str
    async def initialize(self) -> dict[str, Any]: ...
    def needs_refresh(self, log_remaining_time: bool = False) -> bool: ...
    def get_last_refresh_time(self) -> float: ...
    async def refresh(self) -> None: ...
    async def update(self) -> bool: ...
    async def rollback(self) -> bool: ...
    def get_update_status(self) -> dict[str, Any]: ...
    def get_persistent_data(self) -> dict[str, Any]: ...
    def log_exc(self, msg: str, traceback: bool = True) -> ServerError: ...
    def log_info(self, msg: str) -> None: ...
    def log_debug(self, msg: str) -> None: ...
    def notify_status(self, msg: str, is_complete: bool = False) -> None: ...
    def close(self) -> Coroutine | None: ...
