import asyncio
import pathlib
from ...confighelper import ConfigHelper as ConfigHelper
from ...utils.versions import GitVersion as GitVersion
from ..http_client import HttpClient as HttpClient
from ..shell_command import ShellCommand as ShellCommand
from .app_deploy import AppDeploy as AppDeploy
from .common import Channel as Channel
from .update_manager import CommandHelper as CommandHelper
from _typeshed import Incomplete
from typing import Any

class GitDeploy(AppDeploy):
    origin: str
    moved_origin: str | None
    primary_branch: Incomplete
    repo: Incomplete
    def __init__(self, config: ConfigHelper) -> None: ...
    async def initialize(self) -> dict[str, Any]: ...
    async def refresh(self) -> None: ...
    async def update(self) -> bool: ...
    async def recover(self, hard: bool = False, force_dep_update: bool = False) -> None: ...
    async def rollback(self) -> bool: ...
    def get_update_status(self) -> dict[str, Any]: ...
    def get_persistent_data(self) -> dict[str, Any]: ...

GIT_ASYNC_TIMEOUT: float
GIT_ENV_VARS: Incomplete
GIT_MAX_LOG_CNT: int
GIT_LOG_FMT: str
GIT_REF_FMT: str
SRC_EXTS: Incomplete

class GitRepo:
    server: Incomplete
    cmd_helper: Incomplete
    alias: Incomplete
    src_path: Incomplete
    backup_path: Incomplete
    git_folder_path: Incomplete
    origin_url: Incomplete
    moved_origin_url: Incomplete
    primary_branch: Incomplete
    recovery_message: Incomplete
    repo_warnings: list[str]
    repo_anomalies: list[str]
    init_evt: asyncio.Event | None
    initialized: bool
    git_operation_lock: Incomplete
    fetch_timeout_handle: asyncio.Handle | None
    fetch_input_recd: bool
    channel: Incomplete
    pinned_commit: Incomplete
    is_shallow: bool
    def __init__(self, cmd_helper: CommandHelper, src_path: pathlib.Path, alias: str, origin_url: str, moved_origin_url: str | None, primary_branch: str, channel: Channel, pinned_commit: str | None) -> None: ...
    valid_git_repo: bool
    git_owner: str
    git_repo_name: str
    git_remote: str
    git_branch: str
    current_version: Incomplete
    upstream_version: Incomplete
    current_commit: str
    upstream_commit: str
    upstream_url: str
    recovery_url: str
    branches: list[str]
    head_detached: bool
    git_messages: list[str]
    commits_behind: list[dict[str, Any]]
    commits_behind_count: int
    diverged: bool
    repo_corrupt: bool
    modified_files: list[str]
    untracked_files: list[str]
    rollback_commit: str
    rollback_branch: str
    rollback_version: Incomplete
    pinned_commit_valid: bool
    async def restore_state(self, storage: dict[str, Any]) -> None: ...
    def get_persistent_data(self) -> dict[str, Any]: ...
    async def refresh_repo_state(self, need_fetch: bool = True) -> None: ...
    async def wait_for_init(self) -> None: ...
    async def is_ancestor(self, ancestor_ref: str, descendent_ref: str, attempts: int = 3) -> bool: ...
    async def check_diverged(self) -> bool: ...
    def log_repo_info(self) -> None: ...
    async def reset(self, ref: str | None = None) -> None: ...
    async def fetch(self) -> None: ...
    async def clean(self) -> None: ...
    async def pull(self) -> None: ...
    async def list_branches(self) -> list[str]: ...
    async def check_commit_exists(self, commit: str) -> bool: ...
    async def remote(self, command: str = '', validate: bool = False) -> str: ...
    async def describe(self, args: str = '') -> str: ...
    async def rev_parse(self, args: str = '') -> str: ...
    async def rev_list(self, args: str = '') -> str: ...
    async def config_get(self, key: str, pattern: str = '', get_all: bool = False, local_only: bool = False) -> str | None: ...
    async def config_set(self, key: str, value: str) -> None: ...
    async def config_add(self, key: str, value: str) -> None: ...
    async def config_unset(self, key: str, pattern: str = '', unset_all: bool = False) -> None: ...
    async def config_cmd(self, args: str) -> str: ...
    async def checkout(self, branch: str | None = None) -> None: ...
    async def run_fsck(self) -> None: ...
    async def clone(self) -> None: ...
    async def rollback(self) -> bool: ...
    def capture_state_for_rollback(self) -> dict[str, Any]: ...
    def set_rollback_state(self, rb_state: dict[str, Any] | None) -> None: ...
    async def get_commits_behind(self) -> list[dict[str, Any]]: ...
    async def get_tagged_commits(self, count: int = 100) -> dict[str, str]: ...
    def get_repo_status(self, rpt_anomalies: bool) -> dict[str, Any]: ...
    def get_version(self, upstream: bool = False) -> GitVersion: ...
    def is_detached(self) -> bool: ...
    def is_dirty(self) -> bool: ...
    def is_current(self) -> bool: ...
    def is_submodule_or_worktree(self): ...
    def is_valid(self) -> bool: ...
    def is_damaged(self) -> bool: ...
    def has_recoverable_errors(self) -> bool: ...
    def get_repo_type(self) -> str: ...
    async def get_recovery_ref(self, upstream_ref: str | None = None) -> str: ...
