import asyncio
from ...confighelper import ConfigHelper as ConfigHelper
from ...thirdparty.packagekit import enums as PkEnum
from ..dbus_manager import DbusManager as DbusManager
from ..machine import Machine as Machine
from .base_deploy import BaseDeploy as BaseDeploy
from .update_manager import CommandHelper as CommandHelper
from _typeshed import Incomplete
from dbus_fast import Variant as Variant
from dbus_fast.aio import ProxyInterface as ProxyInterface
from typing import Any, Awaitable

JsonType = list[Any] | dict[str, Any]

class PackageDeploy(BaseDeploy):
    use_packagekit: Incomplete
    available_packages: list[str]
    def __init__(self, config: ConfigHelper) -> None: ...
    prefix: str
    provider: Incomplete
    async def initialize(self) -> dict[str, Any]: ...
    async def refresh(self) -> None: ...
    def get_persistent_data(self) -> dict[str, Any]: ...
    async def update(self) -> bool: ...
    async def install_packages(self, package_list: list[str], **kwargs) -> None: ...
    def get_update_status(self) -> dict[str, Any]: ...

class BasePackageProvider:
    server: Incomplete
    cmd_helper: Incomplete
    def __init__(self, cmd_helper: CommandHelper) -> None: ...
    async def initialize(self) -> None: ...
    async def refresh_packages(self, notify: bool = False) -> None: ...
    async def get_packages(self) -> list[str]: ...
    async def install_packages(self, package_list: list[str], **kwargs) -> None: ...
    async def upgrade_system(self) -> None: ...

class AptCliProvider(BasePackageProvider):
    APT_CMD: str
    async def refresh_packages(self, notify: bool = False) -> None: ...
    async def get_packages(self) -> list[str]: ...
    async def resolve_packages(self, package_list: list[str]) -> list[str]: ...
    async def install_packages(self, package_list: list[str], **kwargs) -> None: ...
    async def upgrade_system(self) -> None: ...

class PackageKitProvider(BasePackageProvider):
    dbus_mgr: Incomplete
    pkgkit: ProxyInterface | None
    def __init__(self, cmd_helper: CommandHelper) -> None: ...
    async def initialize(self) -> None: ...
    async def refresh_packages(self, notify: bool = False) -> None: ...
    async def get_packages(self) -> list[str]: ...
    async def install_packages(self, package_list: list[str], **kwargs) -> None: ...
    async def upgrade_system(self) -> None: ...
    def create_transaction(self) -> PackageKitTransaction: ...
    async def run_transaction(self, method: str, *args, notify: bool = False) -> Any: ...

class PackageKitTransaction:
    GET_PKG_ROLES: Incomplete
    QUERY_ROLES: Incomplete
    PROGRESS_STATUS: Incomplete
    server: Incomplete
    eventloop: Incomplete
    cmd_helper: Incomplete
    dbus_mgr: Incomplete
    pkgkit: Incomplete
    notify: bool
    speed: int
    elapsed_time: int
    remaining_time: int
    caller_active: bool
    allow_cancel: bool
    uid: int
    tfut: asyncio.Future | None
    last_progress_notify_time: float
    result: list[dict[str, Any]]
    err_msg: str
    def __init__(self, dbus_mgr: DbusManager, pkgkit: ProxyInterface, cmd_helper: CommandHelper) -> None: ...
    def run(self, method: str, *args, notify: bool = False) -> Awaitable: ...
    @property
    def role(self) -> PkEnum.Role: ...
    @role.setter
    def role(self, role_code: int) -> None: ...
    @property
    def status(self) -> PkEnum.Status: ...
    @status.setter
    def status(self, status_code: int) -> None: ...
    @property
    def transaction_flags(self) -> PkEnum.TransactionFlag: ...
    @transaction_flags.setter
    def transaction_flags(self, bits: int) -> None: ...
    @property
    def percentage(self) -> int: ...
    @percentage.setter
    def percentage(self, percent: int) -> None: ...
    @property
    def download_size_remaining(self) -> int: ...
    @download_size_remaining.setter
    def download_size_remaining(self, bytes_remaining: int) -> None: ...
