import asyncio
import tempfile
from ...common import RequestType as RequestType, WebRequest as WebRequest
from ...confighelper import ConfigHelper as ConfigHelper
from ...eventloop import FlexTimer as FlexTimer
from ...server import Server as Server
from ...utils.filelock import AsyncExclusiveFileLock as AsyncExclusiveFileLock, LockTimeout as LockTimeout
from ..database import NamespaceWrapper as NamespaceWrapper
from ..http_client import HttpClient as HttpClient
from ..klippy_connection import KlippyConnection as KlippyConnection
from ..machine import Machine as Machine
from ..shell_command import ShellCommandFactory as SCMDComp
from .app_deploy import AppDeploy as AppDeploy
from .base_deploy import BaseDeploy as BaseDeploy
from .common import AppType as AppType, get_base_configuration as get_base_configuration
from .git_deploy import GitDeploy as GitDeploy
from .net_deploy import NetDeploy as NetDeploy
from .python_deploy import PythonDeploy as PythonDeploy
from .system_deploy import PackageDeploy as PackageDeploy
from _typeshed import Incomplete
from typing import Any, Callable

JsonType = list[Any] | dict[str, Any]
UPDATE_REFRESH_INTERVAL: float

def get_deploy_class(app_type: AppType | str, default: _T) -> type[BaseDeploy] | _T: ...

class UpdateManager:
    server: Incomplete
    event_loop: Incomplete
    instance_tracker: Incomplete
    kconn: KlippyConnection
    app_config: Incomplete
    refresh_window: Incomplete
    cmd_helper: Incomplete
    updaters: dict[str, BaseDeploy]
    cmd_request_lock: Incomplete
    initial_refresh_complete: bool
    klippy_identified_evt: asyncio.Event | None
    refresh_timer: FlexTimer | None
    def __init__(self, config: ConfigHelper) -> None: ...
    def get_updaters(self) -> dict[str, BaseDeploy]: ...
    async def component_init(self) -> None: ...
    def register_updater(self, name: str, config: dict[str, str]) -> None: ...
    async def refresh_updater(self, updater_name: str, force: bool = False) -> None: ...
    async def close(self) -> None: ...

class CommandHelper:
    server: Incomplete
    get_updaters: Incomplete
    http_client: HttpClient
    pkg_updater: PackageDeploy | None
    umdb: Incomplete
    refresh_interval: Incomplete
    gh_rate_limit: int | None
    gh_limit_remaining: int | None
    gh_limit_reset_time: float | None
    cur_update_app: str | None
    cur_update_id: int | None
    full_update: bool
    full_complete: bool
    pending_service_restarts: set[str]
    def __init__(self, config: ConfigHelper, get_updater_cb: Callable[[], dict[str, BaseDeploy]]) -> None: ...
    def get_server(self) -> Server: ...
    def get_shell_command(self) -> SCMDComp: ...
    def get_http_client(self) -> HttpClient: ...
    def get_refresh_interval(self) -> float: ...
    def get_umdb(self) -> NamespaceWrapper: ...
    def set_update_info(self, app: str, uid: int, full: bool = False) -> None: ...
    def is_full_update(self) -> bool: ...
    def add_pending_restart(self, svc_name: str) -> None: ...
    def remove_pending_restart(self, svc_name: str) -> None: ...
    def set_full_complete(self, complete: bool = False): ...
    def clear_update_info(self) -> None: ...
    def needs_service_restart(self, svc_name: str) -> bool: ...
    def is_app_updating(self, app_name: str) -> bool: ...
    def is_update_busy(self) -> bool: ...
    def set_package_updater(self, updater: PackageDeploy) -> None: ...
    async def run_cmd(self, cmd: str, timeout: float = 20.0, notify: bool = False, attempts: int = 1, env: dict[str, str] | None = None, cwd: str | None = None, sig_idx: int = 1, log_stderr: bool = False) -> None: ...
    def notify_update_refreshed(self) -> None: ...
    def notify_update_response(self, resp: str | bytes, is_complete: bool = False) -> None: ...
    async def install_packages(self, package_list: list[str], **kwargs) -> None: ...
    def get_rate_limit_stats(self) -> dict[str, Any]: ...
    def on_download_progress(self, progress: int, download_size: int, downloaded: int) -> None: ...
    async def create_tempdir(self, suffix: str | None = None, prefix: str | None = None) -> tempfile.TemporaryDirectory[str]: ...

class InstanceTracker:
    server: Incomplete
    inst_id: str
    inst_file_path: Incomplete
    def __init__(self, server: Server) -> None: ...
    def get_instance_id(self) -> str: ...
    async def set_instance_id(self) -> None: ...
    async def close(self) -> None: ...

def load_component(config: ConfigHelper) -> UpdateManager: ...
