import asyncio
import pathlib
from ...common import RequestType as RequestType, TransportType as TransportType, UserInfo as UserInfo, WebRequest as WebRequest
from ...confighelper import ConfigHelper as ConfigHelper
from ...utils import source_info as source_info
from ..database import MoonrakerDatabase as DBComp
from ..job_queue import JobQueue as JobQueue
from ..job_state import JobState as JobState
from ..klippy_connection import KlippyConnection as KlippyConnection
from ..secrets import Secrets as Secrets
from _typeshed import Incomplete
from typing import Any, Awaitable, Coroutine

StrOrPath = str | pathlib.Path
VALID_GCODE_EXTS: Incomplete
METADATA_SCRIPT: Incomplete
WATCH_FLAGS: Incomplete

class FileManager:
    server: Incomplete
    event_loop: Incomplete
    reserved_paths: dict[str, tuple[pathlib.Path, bool]]
    full_access_roots: set[str]
    file_paths: dict[str, str]
    datapath: Incomplete
    gcode_metadata: Incomplete
    sync_lock: Incomplete
    fs_observer: Incomplete
    scheduled_notifications: dict[str, asyncio.TimerHandle]
    fixed_path_args: dict[str, Any]
    queue_gcodes: bool
    check_klipper_path: Incomplete
    def __init__(self, config: ConfigHelper) -> None: ...
    def start_file_observer(self) -> None: ...
    def validate_gcode_path(self, gc_path: str) -> None: ...
    def register_data_folder(self, folder_name: str, full_access: bool = False) -> pathlib.Path: ...
    def disable_write_access(self) -> None: ...
    def check_write_enabled(self) -> None: ...
    def register_directory(self, root: str, path: str | None, full_access: bool = False) -> bool: ...
    def check_reserved_path(self, req_path: StrOrPath, need_write: bool, raise_error: bool = True) -> bool: ...
    def add_reserved_path(self, name: str, res_path: StrOrPath, read_access: bool = True) -> bool: ...
    def get_directory(self, root: str = 'gcodes') -> str: ...
    def get_registered_dirs(self) -> list[str]: ...
    def get_fixed_path_args(self) -> dict[str, Any]: ...
    def get_relative_path(self, root: str, full_path: str) -> str: ...
    def get_full_path(self, root: str, relative_path: str) -> pathlib.Path: ...
    def get_metadata_storage(self) -> MetadataStorage: ...
    def check_file_exists(self, root: str, filename: str, modified: float | None = None) -> bool: ...
    def can_access_path(self, path: StrOrPath) -> bool: ...
    def upload_queue_enabled(self) -> bool: ...
    def get_path_info(self, path: StrOrPath, root: str, raise_error: bool = True) -> dict[str, Any]: ...
    def gen_temp_upload_path(self) -> str: ...
    async def finalize_upload(self, form_args: dict[str, Any]) -> dict[str, Any]: ...
    def get_file_list(self, root: str, list_format: bool = False) -> dict[str, Any] | list[dict[str, Any]]: ...
    def get_file_metadata(self, filename: str) -> dict[str, Any]: ...
    def list_dir(self, directory: str, simple_format: bool = False) -> dict[str, Any] | list[str]: ...
    async def delete_file(self, path: str) -> dict[str, Any]: ...
    def cancel_notification(self, key: str) -> None: ...
    def close(self) -> None: ...

class NotifySyncLock(asyncio.Lock):
    server: Incomplete
    action: str
    dest_path: pathlib.Path | None
    check_pending: bool
    move_copy_fut: asyncio.Future | None
    sync_waiters: list[asyncio.Future]
    pending_paths: set[pathlib.Path]
    acquired_paths: set[pathlib.Path]
    def __init__(self, config: ConfigHelper) -> None: ...
    def setup(self, action: str, path: StrOrPath, move_copy: bool = False) -> None: ...
    async def wait_inotify_event(self, current_path: StrOrPath) -> None: ...
    def finish(self) -> None: ...
    def add_pending_path(self, action: str, pending_path: StrOrPath) -> None: ...
    def check_in_request(self, action: str, inotify_path: StrOrPath) -> asyncio.Future | None: ...
    def release(self) -> None: ...

class BaseFileSystemObserver:
    server: Incomplete
    event_loop: Incomplete
    enable_warn: Incomplete
    file_manager: Incomplete
    gcode_metadata: Incomplete
    sync_lock: Incomplete
    def __init__(self, config: ConfigHelper, file_manager: FileManager, gcode_metadata: MetadataStorage, sync_lock: NotifySyncLock) -> None: ...
    @property
    def has_fast_observe(self) -> bool: ...
    def initialize(self) -> None: ...
    def add_root_watch(self, root: str, root_path: str) -> None: ...
    def try_move_metadata(self, prev_root: str, new_root: str, prev_path: str, new_path: str, is_dir: bool = False) -> bool | Awaitable: ...
    def clear_metadata(self, root: str, path: str, is_dir: bool = False) -> None: ...
    def parse_gcode_metadata(self, file_path: str) -> asyncio.Event: ...
    def on_item_copy(self, root: str, item_path: StrOrPath) -> Awaitable | None: ...
    def on_item_move(self, src_root: str, dest_root: str, src_path: StrOrPath, dest_path: StrOrPath) -> Awaitable | None: ...
    def on_item_create(self, root: str, item_path: StrOrPath, is_dir: bool = False) -> None: ...
    def on_item_delete(self, root: str, item_path: StrOrPath, is_dir: bool = False) -> None: ...
    def close(self) -> None: ...

INOTIFY_BUNDLE_TIME: float
INOTIFY_MOVE_TIME: float

class InotifyNode:
    iobsvr: Incomplete
    event_loop: Incomplete
    name: Incomplete
    parent_node: Incomplete
    child_nodes: dict[str, InotifyNode]
    watch_desc: Incomplete
    pending_node_events: dict[str, asyncio.Handle]
    pending_deleted_children: set[tuple[str, bool]]
    pending_file_events: dict[str, str]
    queued_move_notificatons: list[list[str]]
    is_processing_metadata: bool
    def __init__(self, iobsvr: InotifyObserver, parent: InotifyNode, name: str) -> None: ...
    def scan_node(self, visited_dirs: set[tuple[int, int]] = ...) -> list[asyncio.Event]: ...
    def move_child_node(self, child_name: str, new_name: str, new_parent: InotifyNode) -> None: ...
    def schedule_file_event(self, file_name: str, evt_name: str) -> None: ...
    def clear_file_event(self, file_name: str) -> str | None: ...
    def complete_file_write(self, file_name: str) -> None: ...
    def add_child_node(self, node: InotifyNode) -> None: ...
    def get_child_node(self, name: str) -> InotifyNode | None: ...
    def pop_child_node(self, name: str) -> InotifyNode | None: ...
    def create_child_node(self, name: str, notify: bool = True) -> InotifyNode | None: ...
    def schedule_child_delete(self, child_name: str, is_node: bool) -> None: ...
    def clear_watches(self) -> None: ...
    def get_path(self) -> str: ...
    def get_root(self) -> str: ...
    def is_processing(self) -> bool: ...
    def has_child_node(self, child_name: str): ...
    def add_event(self, evt_name: str, timeout: float) -> None: ...
    def reset_event(self, evt_name: str, timeout: float) -> None: ...
    def stop_event(self, evt_name: str) -> None: ...
    def remove_event(self, evt_name: str) -> None: ...
    def flush_delete(self) -> None: ...
    def clear_events(self, include_children: bool = True) -> None: ...
    def search_pending_event(self, name: str) -> InotifyNode | None: ...
    def find_pending_node(self) -> InotifyNode | None: ...
    def queue_move_notification(self, args: list[str]) -> None: ...

class InotifyRootNode(InotifyNode):
    root_name: Incomplete
    def __init__(self, iobsvr: InotifyObserver, root_name: str, root_path: str) -> None: ...
    def get_path(self) -> str: ...
    def get_root(self) -> str: ...
    def search_pending_event(self, name) -> InotifyNode | None: ...
    def is_processing(self) -> bool: ...
    def find_pending_node(self) -> InotifyNode | None: ...

class InotifyObserver(BaseFileSystemObserver):
    enable_warn: Incomplete
    inotify: Incomplete
    watched_roots: dict[str, InotifyRootNode]
    watched_nodes: dict[int, InotifyNode]
    pending_moves: dict[int, tuple[InotifyNode, str, asyncio.Handle]]
    initialized: bool
    processing_gcode_files: set[str]
    pending_coroutines: list[Coroutine]
    def __init__(self, config: ConfigHelper, file_manager: FileManager, gcode_metadata: MetadataStorage, sync_lock: NotifySyncLock) -> None: ...
    @property
    def has_fast_observe(self) -> bool: ...
    def on_item_create(self, root: str, item_path: StrOrPath, is_dir: bool = False) -> None: ...
    def on_item_delete(self, root: str, item_path: StrOrPath, is_dir: bool = False) -> None: ...
    def on_item_move(self, src_root: str, dest_root: str, src_path: StrOrPath, dest_path: StrOrPath) -> Awaitable | None: ...
    def on_item_copy(self, root: str, item_path: StrOrPath) -> Awaitable | None: ...
    def add_root_watch(self, root: str, root_path: str) -> None: ...
    def initialize(self) -> None: ...
    def add_watch(self, node: InotifyNode) -> int: ...
    def remove_watch(self, wdesc: int, need_low_level_rm: bool = True) -> None: ...
    def log_nodes(self) -> None: ...
    def need_create_notify(self, file_path: str) -> bool: ...
    def clear_processing_file(self, file_path: str) -> None: ...
    def queue_gcode_notification(self, coro: Coroutine) -> None: ...
    def notify_filelist_changed(self, action: str, root: str, full_path: str, source_root: str | None = None, source_path: str | None = None) -> None: ...
    def close(self) -> None: ...

METADATA_NAMESPACE: str
METADATA_VERSION: int

class MetadataStorage:
    server: Incomplete
    enable_object_proc: Incomplete
    default_metadata_parser_timeout: Incomplete
    gc_path: str
    mddb: Incomplete
    metadata: dict[str, Any]
    pending_requests: dict[str, tuple[dict[str, Any], asyncio.Event]]
    busy: bool
    processors: dict[str, dict[str, Any]]
    def __init__(self, config: ConfigHelper, db: DBComp) -> None: ...
    def prune_storage(self) -> None: ...
    def update_gcode_path(self, path: str) -> None: ...
    def get(self, key: str, default: _T | None = None) -> _T | dict[str, Any]: ...
    def insert(self, key: str, value: dict[str, Any]) -> None: ...
    def is_processing(self) -> bool: ...
    def is_file_processing(self, fname: str) -> bool: ...
    def register_gcode_processor(self, name: str, config: dict[str, Any] | None) -> None: ...
    def remove_directory_metadata(self, dir_name: str) -> Awaitable | None: ...
    def remove_file_metadata(self, fname: str) -> Awaitable | None: ...
    def move_directory_metadata(self, prev_dir: str, new_dir: str) -> None: ...
    def move_file_metadata(self, prev_fname: str, new_fname: str) -> bool | Awaitable: ...
    def parse_metadata(self, fname: str, path_info: dict[str, Any]) -> asyncio.Event: ...

def load_component(config: ConfigHelper) -> FileManager: ...
