from _typeshed import Incomplete
from typing import Any

READ_SIZE: Incomplete
UFP_MODEL_PATH: str
UFP_THUMB_PATH: str
SUPPORTED_THUMB_FORMATS: Incomplete
FMT_CONV_MAP: Incomplete
logger: Incomplete

def regex_find_floats(pattern: str, data: str) -> list[float]: ...
def regex_find_ints(pattern: str, data: str) -> list[int]: ...
def regex_find_strings(pattern: str, separators: str, data: str) -> list[str]: ...
def regex_find_float(pattern: str, data: str) -> float | None: ...
def regex_find_int(pattern: str, data: str) -> int | None: ...
def regex_find_string(pattern: str, data: str) -> str | None: ...
def regex_find_min_float(pattern: str, data: str) -> float | None: ...
def regex_find_max_float(pattern: str, data: str) -> float | None: ...

class BaseSlicer:
    path: Incomplete
    slicer_name: str
    slicer_version: str
    header_data: str
    footer_data: str
    layer_height: float | None
    has_m486_objects: bool
    def __init__(self, file_path: str) -> None: ...
    size: int
    def set_data(self, file_data: str, fsize: int) -> None: ...
    def check_identity(self, data: str) -> bool: ...
    def check_gcode_processor(self, regex: str, location: str) -> dict[str, Any] | None: ...
    def has_objects(self) -> bool: ...
    def parse_gcode_start_byte(self) -> int | None: ...
    def parse_gcode_end_byte(self) -> int | None: ...
    def parse_first_layer_height(self) -> float | None: ...
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_filament_weight_total(self) -> float | None: ...
    def parse_filament_weights(self) -> list[float] | None: ...
    def parse_filament_name(self) -> str | None: ...
    def parse_filament_type(self) -> str | None: ...
    def parse_filament_colors(self) -> list[str] | None: ...
    def parse_extruder_colors(self) -> list[str] | None: ...
    def parse_filament_temps(self) -> list[int] | None: ...
    def parse_referenced_tools(self) -> list[int] | None: ...
    def parse_mmu_print(self) -> int | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_chamber_temp(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_filament_change_count(self) -> int | None: ...
    def parse_thumbnails(self) -> list[dict[str, Any]] | None: ...
    def parse_layer_count(self) -> int | None: ...
    def parse_nozzle_diameter(self) -> float | None: ...

class UnknownSlicer(BaseSlicer):
    def parse_first_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_chamber_temp(self) -> float | None: ...

class PrusaSlicer(BaseSlicer):
    slicer_name: Incomplete
    slicer_version: Incomplete
    def check_identity(self, data: str) -> bool: ...
    def has_objects(self) -> bool: ...
    def parse_first_layer_height(self) -> float | None: ...
    layer_height: Incomplete
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_filament_weight_total(self) -> float | None: ...
    def parse_filament_weights(self) -> list[float] | None: ...
    def parse_filament_type(self) -> str | None: ...
    def parse_filament_name(self) -> str | None: ...
    def parse_filament_colors(self) -> list[str] | None: ...
    def parse_extruder_colors(self) -> list[str] | None: ...
    def parse_filament_temps(self) -> list[int] | None: ...
    def parse_referenced_tools(self) -> list[int] | None: ...
    def parse_mmu_print(self) -> int | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_chamber_temp(self) -> float | None: ...
    def parse_nozzle_diameter(self) -> float | None: ...
    def parse_layer_count(self) -> int | None: ...
    def parse_filament_change_count(self) -> int | None: ...

class Slic3rPE(PrusaSlicer):
    slicer_name: str
    slicer_version: Incomplete
    def check_identity(self, data: str) -> bool: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_thumbnails(self) -> list[dict[str, Any]] | None: ...

class Slic3r(Slic3rPE):
    slicer_name: str
    slicer_version: Incomplete
    def check_identity(self, data: str) -> bool: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_filament_weight_total(self) -> float | None: ...
    def parse_estimated_time(self) -> float | None: ...

class Cura(BaseSlicer):
    slicer_name: str
    slicer_version: Incomplete
    def check_identity(self, data: str) -> bool: ...
    def has_objects(self) -> bool: ...
    def parse_first_layer_height(self) -> float | None: ...
    layer_height: Incomplete
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_filament_weight_total(self) -> float | None: ...
    def parse_filament_weights(self) -> list[float] | None: ...
    def parse_filament_type(self) -> str | None: ...
    def parse_filament_name(self) -> str | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_chamber_temp(self) -> float | None: ...
    def parse_layer_count(self) -> int | None: ...
    def parse_nozzle_diameter(self) -> float | None: ...
    def parse_thumbnails(self) -> list[dict[str, Any]] | None: ...

class Simplify3D(BaseSlicer):
    slicer_name: str
    slicer_version: Incomplete
    def check_identity(self, data: str) -> bool: ...
    def parse_first_layer_height(self) -> float | None: ...
    layer_height: Incomplete
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_filament_weight_total(self) -> float | None: ...
    def parse_filament_name(self) -> str | None: ...
    def parse_filament_type(self) -> str | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_nozzle_diameter(self) -> float | None: ...

class KISSlicer(BaseSlicer):
    slicer_name: str
    slicer_version: Incomplete
    def check_identity(self, data: str) -> bool: ...
    def parse_first_layer_height(self) -> float | None: ...
    layer_height: Incomplete
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_chamber_temp(self) -> float | None: ...

class IdeaMaker(BaseSlicer):
    slicer_name: str
    slicer_version: Incomplete
    def check_identity(self, data: str) -> bool: ...
    def has_objects(self) -> bool: ...
    def parse_first_layer_height(self) -> float | None: ...
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_filament_type(self) -> str | None: ...
    def parse_filament_name(self) -> str | None: ...
    def parse_filament_weight_total(self) -> float | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_chamber_temp(self) -> float | None: ...
    def parse_nozzle_diameter(self) -> float | None: ...

class IceSL(BaseSlicer):
    slicer_name: str
    slicer_version: Incomplete
    def check_identity(self, data) -> bool: ...
    def parse_first_layer_height(self) -> float | None: ...
    layer_height: Incomplete
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...
    def parse_chamber_temp(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_filament_weight_total(self) -> float | None: ...
    def parse_filament_name(self) -> str | None: ...
    def parse_filament_type(self) -> str | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_layer_count(self) -> int | None: ...
    def parse_nozzle_diameter(self) -> float | None: ...

class KiriMoto(BaseSlicer):
    slicer_name: Incomplete
    slicer_version: Incomplete
    def check_identity(self, data) -> bool: ...
    def parse_first_layer_height(self) -> float | None: ...
    layer_height: Incomplete
    def parse_layer_height(self) -> float | None: ...
    def parse_object_height(self) -> float | None: ...
    def parse_layer_count(self) -> int | None: ...
    def parse_estimated_time(self) -> float | None: ...
    def parse_filament_total(self) -> float | None: ...
    def parse_first_layer_extr_temp(self) -> float | None: ...
    def parse_first_layer_bed_temp(self) -> float | None: ...

SUPPORTED_SLICERS: list[type[BaseSlicer]]
SUPPORTED_DATA: Incomplete
PPC_REGEX: str

def process_objects(file_path: str, slicer: BaseSlicer) -> bool: ...
def get_slicer(file_path: str) -> BaseSlicer: ...
def run_gcode_processors(gc_file_path: str, slicer: BaseSlicer, processors: list[dict[str, Any]]) -> tuple[list[str], bool]: ...
def extract_metadata(file_path: str, processors: list[dict[str, Any]]) -> dict[str, Any]: ...
def extract_ufp(ufp_path: str, dest_path: str) -> None: ...
def main(config: dict[str, Any]) -> None: ...
